# MUST HAVE
- 컬럼 값 자체에 dict 형식이 들어있는 경우, 데이터프레임으로 따로 빼서 처리하기

In [1]:
import requests
import json

In [11]:
import pprint

In [235]:
import warnings
warnings.filterwarnings('ignore')

In [672]:
import pandas as pd
from pandas.io.json import json_normalize

## 01. 서버 정보

In [669]:
url = 'https://api.neople.co.kr/df/servers?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [670]:
response = requests.get(url)
contents = response.text

In [671]:
pp = pprint.PrettyPrinter(indent=1)
print(pp.pprint(contents))

'{"rows":[{"serverId":"cain","serverName":"카인"},{"serverId":"diregie","serverName":"디레지에"},{"serverId":"siroco","serverName":"시로코"},{"serverId":"prey","serverName":"프레이"},{"serverId":"casillas","serverName":"카시야스"},{"serverId":"hilder","serverName":"힐더"},{"serverId":"anton","serverName":"안톤"},{"serverId":"bakal","serverName":"바칼"}]}'
None

In [673]:
json_ob = json.loads(contents)
body = json_ob['rows']
dataframe = json_normalize(body)
print(dataframe)

   serverId serverName
0      cain         카인
1   diregie       디레지에
2    siroco        시로코
3      prey        프레이
4  casillas       카시야스
5    hilder         힐더
6     anton         안톤
7     bakal         바칼

In [675]:
dataframe.to_csv('DnF_server.csv')

## 02. 캐릭터 검색
- characterId = 유저명 (ex. 노블레스, 열진)
https://meyerweb.com/eric/tools/dencoder/
- wordType=full로 해야 해당 글자가 들어있는 모든 유저에 대한 정보를 가져올 수 있음

In [761]:
name = '%eb%85%b8%eb%b8%94%eb%a0%88%ec%8a%a4' # 유저 '노블레스'
url = 'https://api.neople.co.kr/df/servers/all/characters?characterName={0}&limit=200&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'.format(name)

In [1179]:
url = 'https://api.neople.co.kr/df/servers/all/characters?characterName=%EA%B0%80%EC%97%B0&wordType=full&limit=200&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [1180]:
response = requests.get(url)
contents = response.text

In [1181]:
json_ob = json.loads(contents)
#print(json_ob)
#print(type(json_ob))

In [1182]:
len(json_ob['rows'])

200

In [1183]:
dataframe2 = json_normalize(json_ob['rows'])
#print(dataframe)

In [1184]:
dataframe2.to_csv('02_chr_가연_full.csv')

In [1185]:
dataframe2

,serverId,characterId,characterName,level,jobId,jobGrowId,jobName,jobGrowName
0,cain,9d5eec1cc34396b90d018eb36747e2fa,가연,1,a7a059ebe9e6054c0644b40ef316d6e9,1ea40db11ff66e70bcb0add7fae44cdb,격투가(여),격투가(여)
1,diregie,a7271130e7c294cda6bc764831ff7226,가연,100,0ee8fa5dc525c1a1f23fc6911e921e4a,c9b492038ee3ca8d27d7004cf58d59f3,나이트,眞 드래곤나이트
2,siroco,be95c62529e65c069284ae9ff2241607,가연,45,3909d0b188e9c95311399f776e331da5,1ea78ae210f681a799feb4403a5c1e85,마법사(여),소환사
3,prey,0054f1492fff4ed4d848ef6dc163abc1,가연,90,1645c45aabb008c98406b3a16447040d,64bbd751c0fcae0e74758b871a2296c1,귀검사(여),검제
4,casillas,0881b4d6193b2cbe825afc3fac7031f6,가연,44,944b9aab492c15a8474f96947ceeb9e4,a9a4ef4552d46e39cf6c874a51126410,거너(여),메카닉
...,...,...,...,...,...,...,...,...
195,hilder,0870911358d72cd1e61ca60b3340a8c5,선우가연,80,3909d0b188e9c95311399f776e331da5,8022a99e29b5e4845985fe1d79a233f3,마법사(여),이클립스
196,hilder,ca67a0ca8d9bc05463d21216046652e4,덮혹가연,91,41f1cdc2ff58bb5fdc287be0db2a8df3,64bbd751c0fcae0e74758b871a2296c1,귀검사(남),인다라천
197,hilder,1fd03589e634fe980bdf791cd6d67c39,가연공주,27,944b9aab492c15a8474f96947ceeb9e4,1ea78ae210f681a799feb4403a5c1e85,거너(여),런처
198,siroco,9ba088abb4b4d8d02a982027c3f915fb,원가연,40,ddc49e9ad1ff72a00b53c6cff5b1e920,df3870efe8e8754011cd12fa03cd275f,도적,로그
199,siroco,ec26a2c4dfef1a595fadb7d4326ff0c4,베가연,46,1645c45aabb008c98406b3a16447040d,4a1459a4fa3c7f59b6da2e43382ed0b9,귀검사(여),베가본드

In [767]:
dataframe.to_csv('02_character.csv')

https://api.neople.co.kr/df/servers/all/characters?characterName=%eb%9f%b0%ec%b2%98&limit=10&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25
- 런처 : %eb%9f%b0%ec%b2%98
- 거너 : %ea%b1%b0%eb%84%88
- 웨펀마스터 : %ec%9b%a8%ed%8e%80%eb%a7%88%ec%8a%a4%ed%84%b0
- 노블레스 : %eb%85%b8%eb%b8%94%eb%a0%88%ec%8a%a4

In [112]:
dataframe

,serverId,characterId,characterName,level,jobId,jobGrowId,jobName,jobGrowName
0,cain,ad34d7a0b8c7267b8f921c79e57ddebd,노블레스,110,0c1b401bb09241570d364420b3ba3fd7,37495b941da3b1661bc900e68ef3b2c6,프리스트(여),眞 크루세이더
1,diregie,ac15f0bb7506780b3bf93eac1238be42,노블레스,100,0c1b401bb09241570d364420b3ba3fd7,37495b941da3b1661bc900e68ef3b2c6,프리스트(여),眞 크루세이더
2,siroco,eae73c7fd124ec46ef65fa5ab64068c8,노블레스,100,3deb7be5f01953ac8b1ecaa1e25e0420,64bbd751c0fcae0e74758b871a2296c1,마창사,에레보스
3,prey,1cd879a30e8ada668ec8e2f64b98a0a5,노블레스,100,3909d0b188e9c95311399f776e331da5,618326026de1a1f1cfba5dbd0b8396e7,마법사(여),眞 소환사
4,casillas,15b3dc5a1b5b47777d36f9bfb8c68e44,노블레스,70,41f1cdc2ff58bb5fdc287be0db2a8df3,460822c3780a9bc3fbe9485cc89c44a4,귀검사(남),헬벤터
5,hilder,e231b31cf4f6d0fbcbefc5098fef7ccd,노블레스,110,1645c45aabb008c98406b3a16447040d,37495b941da3b1661bc900e68ef3b2c6,귀검사(여),眞 소드마스터
6,anton,6715687949e1277b7e89f1cce57cb3a2,노블레스,110,1645c45aabb008c98406b3a16447040d,37495b941da3b1661bc900e68ef3b2c6,귀검사(여),眞 소드마스터
7,bakal,9cb1b3fd48e24cd8a992d1a8b497ecc3,노블레스,110,1645c45aabb008c98406b3a16447040d,37495b941da3b1661bc900e68ef3b2c6,귀검사(여),眞 소드마스터

### 특정 캐릭터를 사용하는 유저의 정보
- serverId : 서버
- characterId : 유저 아이디
- characterName : 캐릭터 이름
- level : 레벨
- jobId : 캐릭터 직업 고유 코드
- jobGrowId : 캐릭터 각성 직업 고유 코드

## 03. 캐릭터 기본 정보 조회
- 위 데이터 프레임의 0행에 해당하는 characterId (ad34d7a0b8c7267b8f921c79e57ddebd)

In [768]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [769]:
response = requests.get(url)
contents = response.text
pp = pprint.PrettyPrinter(indent=4)
json_ob = json.loads(contents)

In [770]:
json_ob

{'characterId': 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'characterName': '노블레스',
 'level': 110,
 'jobId': '0c1b401bb09241570d364420b3ba3fd7',
 'jobGrowId': '37495b941da3b1661bc900e68ef3b2c6',
 'jobName': '프리스트(여)',
 'jobGrowName': '眞 크루세이더',
 'adventureName': 'Ocsusu',
 'guildId': '42dfa2d420111ee9854bbee20b28ea6c',
 'guildName': '꽃과뱀'}

In [771]:
dataframe = json_normalize(json_ob)

In [773]:
dataframe.to_csv('03_chr_info.csv')

## 04. 캐릭터 타임라인 정보 조회

In [778]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd//timeline?startDate=20230227T0000&endDate=20230327T2359&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [779]:
response = requests.get(url)
contents = response.text
pp = pprint.PrettyPrinter(indent=4)
json_ob = json.loads(contents)

In [780]:
json_ob

{'characterId': 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'characterName': '노블레스',
 'level': 110,
 'jobId': '0c1b401bb09241570d364420b3ba3fd7',
 'jobGrowId': '37495b941da3b1661bc900e68ef3b2c6',
 'jobName': '프리스트(여)',
 'jobGrowName': '眞 크루세이더',
 'adventureName': 'Ocsusu',
 'guildId': '42dfa2d420111ee9854bbee20b28ea6c',
 'guildName': '꽃과뱀',
 'timeline': {'date': {'start': '2023-02-27 00:00', 'end': '2023-03-27 23:59'},
  'next': '44c5e0834d52fc77499bb759dfdceb92d19fdca43d94b8275164f618dca215ef3dc2714dc8217afc6bcd630ddcd0a03ff08a7b65b76b8c5e4ce4349c004fb5fd8eeae24853bfa7c1b21773fd7701718da0d0fa5d770e6402906d92c40ab41f46',
  'rows': [{'code': 507,
    'name': '아이템 획득(레이드 카드 보상)',
    'date': '2023-03-26 21:39',
    'data': {'itemId': '1aa5c0faf9bcd968077f5787ac3a430b',
     'itemName': '근원을 삼킨 십자가',
     'itemRarity': '에픽'}},
   {'code': 507,
    'name': '아이템 획득(레이드 카드 보상)',
    'date': '2023-03-26 21:39',
    'data': {'itemId': '53dff026d8600429a488ad25095b9692',
     'itemName': '엔트 정령의 목걸이',
     'itemRarity': '에픽'}},
   {'code': 507,
    'name': '아이템 획득(레이드 카드 보상)',
    'date': '2023-03-26 21:39',
    'data': {'itemId': '9ff0e3c1d81691de5b7064d7b53e5236',
     'itemName': '블루 베릴 보호대',
     'itemRarity': '에픽'}},
   {'code': 507,
    'name': '아이템 획득(레이드 카드 보상)',
    'date': '2023-03-26 21:39',
    'data': {'itemId': '17b4154346de02a3deb7c49997a2736b',
     'itemName': '과거를 뒤로 한 전진',
     'itemRarity': '에픽'}},
   {'code': 507,
    'name': '아이템 획득(레이드 카드 보상)',
    'date': '2023-03-26 21:39',
    'data': {'itemId': '0df27e01e5151bc1d62185ff804a5bf8',
     'itemName': '굳건한 믿음',
     'itemRarity': '에픽'}},
   {'code': 201,
    'name': '레이드',
    'date': '2023-03-26 21:39',
    'data': {'raidName': '기계 혁명',
     'raidPartyName': '수수#7/474클/랏딜',
     'modeName': '바칼 레이드'}},
   {'code': 505,
    'name': '아이템 획득(던전 드랍)',
    'date': '2023-03-24 22:01',
    'data': {'itemId': '137e00b2550a315e44eb5cf7d119aa0e',
     'itemName': '스톰라이더',
     'itemRarity': '에픽',
     'channelName': '차원회랑',
     'channelNo': 167,
     'dungeonName': '1계 - 선계'}},
   {'code': 209,
    'name': '레기온 클리어',
    'date': '2023-03-24 22:01',
    'data': {'regionName': '차원회랑'}},
   {'code': 505,
    'name': '아이템 획득(던전 드랍)',
    'date': '2023-03-24 21:59',
    'data': {'itemId': 'd48cae439d3d23c1d60885b45c7ff15b',
     'itemName': '딥 다이버 네비게이션 링',
     'itemRarity': '에픽',
     'channelName': '차원회랑',
     'channelNo': 167,
     'dungeonName': '0계 - 뒤집힌 멸망의 세계'}},
   {'code': 505,
    'name': '아이템 획득(던전 드랍)',
    'date': '2023-03-24 21:58',
    'data': {'itemId': '561de2a9165833cff09d768a6987a0e6',
     'itemName': '자신감의 백색 망토',
     'itemRarity': '에픽',
     'channelName': '차원회랑',
     'channelNo': 167,
     'dungeonName': '6계 - 지옥'}}]}}

In [829]:
dataframe = json_normalize(json_ob)

In [842]:
dataframe.to_csv('04_chr_timeline.csv')

In [831]:
df_t = pd.DataFrame(dataframe['timeline.rows'][0])#['data'][0]

In [838]:
chr_id = []

for i in range(0, len(df_t)):
    chr_id.append(dataframe['characterId'][0])

In [839]:
chr_id

['ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd',
 'ad34d7a0b8c7267b8f921c79e57ddebd']

In [819]:
json_normalize(df_t['data'][0])

                             itemId    itemName itemRarity
0  1aa5c0faf9bcd968077f5787ac3a430b  근원을 삼킨 십자가         에픽

In [840]:
df_t['characterId'] = chr_id

In [843]:
df_t.to_csv('04-2_log.csv')

In [822]:
item_df = pd.DataFrame(columns=['itemId', 'itemName', 'itemRarity'])
for i in range(0, len(df_t)):
    print(json_normalize(df_t['data'][i]))

                             itemId    itemName itemRarity
0  1aa5c0faf9bcd968077f5787ac3a430b  근원을 삼킨 십자가         에픽
                             itemId    itemName itemRarity
0  53dff026d8600429a488ad25095b9692  엔트 정령의 목걸이         에픽
                             itemId   itemName itemRarity
0  9ff0e3c1d81691de5b7064d7b53e5236  블루 베릴 보호대         에픽
                             itemId     itemName itemRarity
0  17b4154346de02a3deb7c49997a2736b  과거를 뒤로 한 전진         에픽
                             itemId itemName itemRarity
0  0df27e01e5151bc1d62185ff804a5bf8   굳건한 믿음         에픽
  raidName raidPartyName modeName
0    기계 혁명  수수#7/474클/랏딜   바칼 레이드
                             itemId itemName itemRarity channelName  \
0  137e00b2550a315e44eb5cf7d119aa0e    스톰라이더         에픽        차원회랑

   channelNo dungeonName
0        167     1계 - 선계
  regionName
0       차원회랑
                             itemId       itemName itemRarity channelName  \
0  d48cae439d3d23c1d60885b45c7ff15b  딥 다이버 네비게이션 링         에픽        차원회랑

   channelNo      dungeonName
0        167  0계 - 뒤집힌 멸망의 세계
                             itemId    itemName itemRarity channelName  \
0  561de2a9165833cff09d768a6987a0e6  자신감의 백색 망토         에픽        차원회랑

   channelNo dungeonName
0        167     6계 - 지옥

In [806]:
(pd.DataFrame.from_records([pd.DataFrame(dataframe['timeline.rows'][0])['data'][i]]))

                             itemId    itemName itemRarity
0  1aa5c0faf9bcd968077f5787ac3a430b  근원을 삼킨 십자가         에픽

## 05. 캐릭터 능력치 정보 조회
- 능력치 정보의 경우 최근 인게임 접속 기준으로 갱신되며, 캐릭터 접속 환경 및 다양한 조건에 따라서 오차 또는 미 제공될 수 있습니다.

In [852]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/status?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [853]:
response = requests.get(url)
contents = response.text
pp = pprint.PrettyPrinter(indent=4)
json_ob = json.loads(contents)

In [854]:
dataframe = json_normalize(json_ob)

In [859]:
dataframe.to_csv('05_chr_status.csv')

In [860]:
json_normalize(dataframe['buff'][0]).to_csv('05-2_chr_buff.csv')

In [861]:
json_normalize(dataframe['status'][0]).to_csv('05-3_chr_status_val.csv')

## 06. 캐릭터 장착 장비 조회

In [862]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/equip/equipment?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [863]:
response = requests.get(url)
contents = response.text
pp = pprint.PrettyPrinter(indent=4)
json_ob = json.loads(contents)

In [864]:
for i in range(0, len(json_ob['equipment'])):
    print('장착 무기 %d'%i, json_ob['equipment'][i]['itemName'])

장착 무기 0 결전의 십자가 - 크루세이더(여)
장착 무기 1 진정한 각성을 이룬 자
장착 무기 2 엔트 정령의 상의
장착 무기 3 주체할 수 없는 낡은 규칙
장착 무기 4 숲속의 마녀 하의
장착 무기 5 엔트 정령의 신발
장착 무기 6 익스펜션 서플라이 벨트
장착 무기 7 폭룡왕의 지배 - 공포
장착 무기 8 딥 다이버 워치
장착 무기 9 어댑터블 투톤 링
장착 무기 10 엔트 정령의 성배
장착 무기 11 엔트 정령의 심장
장착 무기 12 시각의 관점

In [865]:
dataframe = json_normalize(json_ob)

In [868]:
dataframe.to_csv('06_equip.csv')

In [869]:
json_normalize(dataframe['equipment'][0]).to_csv('06-2_equip_detail.csv')

## 07. 캐릭터 장착 아바타 조회

In [870]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/equip/avatar?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [871]:
response = requests.get(url)
contents = response.text
#pp = pprint.PrettyPrinter(indent=4)
json_ob = json.loads(contents)

In [872]:
df = json_normalize(json_ob)

In [873]:
for i in range(0, len(json_ob['avatar'])):
    print('장착 아바타 %d'%i, json_ob['avatar'][i]['itemName'])

장착 아바타 0 레어 모자 클론 아바타
장착 아바타 1 레어 머리 클론 아바타
장착 아바타 2 레어 얼굴 클론 아바타
장착 아바타 3 레어 상의 클론 아바타
장착 아바타 4 레어 하의 클론 아바타
장착 아바타 5 레어 신발 클론 아바타
장착 아바타 6 레어 목가슴 클론 아바타
장착 아바타 7 레어 허리 클론 아바타
장착 아바타 8 [빈티지]베히모스의 해적 여프리스트 뽀얀 피부[A타입]
장착 아바타 9 어워즈 패셔니스타
장착 아바타 10 무기 클론 아바타

In [876]:
df.to_csv('07_chr_avatar.csv')

In [877]:
json_normalize(df['avatar'][0]).to_csv('07-2_avatar_detail.csv')

## 08. 캐릭터 장착 크리쳐 조회

In [878]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/equip/creature?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [879]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [880]:
df = json_normalize(json_ob)

In [883]:
df.to_csv('08_chr_creature.csv')

In [881]:
df.iloc[:, 10:] # 크리쳐의 정보만 추출해보고 싶다

,creature.itemId,creature.itemName,creature.itemRarity,creature.clone.itemId,creature.clone.itemName,creature.artifact
0,f5c87c63bbdaa5413a105640cafbc30a,순백의 나비 공주,레어,abc3c27c407befdf4f04c7bd7c7724b1,쁘띠 마법토끼,"[{'slotColor': 'RED', 'itemName': '와이번의 발톱', '..."

In [884]:
json_normalize(df['creature.artifact'][0]).to_csv('08-2_creature_detail.csv')

In [191]:
for i in range(0, len(df['creature.artifact'][0])):
    print(df['creature.artifact'][0][i])

{'slotColor': 'RED', 'itemName': '와이번의 발톱', 'itemAvailableLevel': 0, 'itemRarity': '언커먼'}
{'slotColor': 'BLUE', 'itemName': '하피의 깃털', 'itemAvailableLevel': 0, 'itemRarity': '언커먼'}
{'slotColor': 'GREEN', 'itemName': '에메랄드 오브', 'itemAvailableLevel': 0, 'itemRarity': '레어'}

## 09. 캐릭터 장착 휘장 조회

In [885]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/equip/flag?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [886]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [887]:
df = json_normalize(json_ob)

In [890]:
df.to_csv('09_chr_flag.csv')

In [891]:
json_normalize(df['flag.gems'][0]).to_csv('09-2_flag_detail.csv')

In [198]:
df.loc[:,'flag.itemId':'flag.gems'] # 휘장에 대한 정보만 볼래!

,flag.itemId,flag.itemName,flag.itemAvailableLevel,flag.itemRarity,flag.reinforce,flag.itemAbility,flag.gems
0,515641617bb0e79fbceb013d0b241a27,완벽한 정기의 문양 휘장,50,레전더리,4,"지능 +48, 독립공격력 +30","[{'slotNo': 1, 'itemId': 'a7840a10a33ca822d76e..."

In [205]:
for i in range(0, len(df['flag.gems'][0])):
    #print(df['flag.gems'][0][i])
    print('Name : ', df['flag.gems'][0][i]['itemName'], '/ Ability : ', df['flag.gems'][0][i]['itemAbility'])

Name :  영롱하게 빛나는 젬[물리방어력] / Ability :  물리방어력 +450
Name :  영롱하게 빛나는 젬[공격속도] / Ability :  공격속도 +3%
Name :  영롱하게 빛나는 젬[명속성강화] / Ability :  명속성강화 +7
Name :  눈부시게 빛나는 젬[마법방어력] / Ability :  마법방어력 +360

## 10. 캐릭처 장착 탈리스만 조회

In [892]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/equip/talisman?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [893]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [894]:
df = json_normalize(json_ob)

In [895]:
df

,characterId,characterName,level,jobId,jobGrowId,jobName,jobGrowName,adventureName,guildId,guildName,talismans
0,ad34d7a0b8c7267b8f921c79e57ddebd,노블레스,110,0c1b401bb09241570d364420b3ba3fd7,37495b941da3b1661bc900e68ef3b2c6,프리스트(여),眞 크루세이더,Ocsusu,42dfa2d420111ee9854bbee20b28ea6c,꽃과뱀,"[{'talisman': {'slotNo': 1, 'itemId': 'e1df635..."

In [896]:
json_normalize(df['talismans'][0])

,runes,talisman.slotNo,talisman.itemId,talisman.itemName,talisman.runeTypes
0,"[{'slotNo': 1, 'itemId': 'e42826a642e9d6adcfbe...",1,e1df6356574c0ef4354b8df5572900d1,카펠라의 성흔 : 찬란한 빛의 구원자,"[테라코타, 서클메이지, 수호자들]"
1,"[{'slotNo': 1, 'itemId': 'e42826a642e9d6adcfbe...",2,0bebc28d7f5386097e7ec4f6256dda2a,카펠라의 성흔 : 천상의 활력소,"[테라코타, 서클메이지, 수호자들]"
2,"[{'slotNo': 1, 'itemId': 'e42826a642e9d6adcfbe...",3,f70164dd7759c7191eeba58d673f4491,카펠라의 성흔 : 우리엘의 가호,"[테라코타, 서클메이지, 수호자들]"

In [897]:
json_normalize(json_normalize(df['talismans'][0])['runes'][0])

   slotNo                            itemId               itemName
0       1  e42826a642e9d6adcfbea775b319a022     화려한 테라코타 룬[치유의 기도]
1       2  007ea0e36fddd07f704da984fdb774f0  화려한 서클 메이지 룬[용맹의 아리아]
2       3  f94d3a8f73de6cdd543e17626a048265    화려한 수호자들 룬[용맹의 아리아]

In [245]:
for i in range(0, len(df['talismans'][0])):
    print(df['talismans'][0][i]['talisman']['itemName'], '/', df['talismans'][0][i]['talisman']['runeTypes'])

카펠라의 성흔 : 찬란한 빛의 구원자 / ['테라코타', '서클메이지', '수호자들']
카펠라의 성흔 : 천상의 활력소 / ['테라코타', '서클메이지', '수호자들']
카펠라의 성흔 : 우리엘의 가호 / ['테라코타', '서클메이지', '수호자들']

## 11. 캐릭터 스킬 스타일 조회

In [246]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/skill/style?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [247]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [248]:
df = json_normalize(json_ob)

In [249]:
df

,characterId,characterName,level,jobId,jobGrowId,jobName,jobGrowName,adventureName,guildId,guildName,skill.style.active,skill.style.passive
0,ad34d7a0b8c7267b8f921c79e57ddebd,노블레스,110,0c1b401bb09241570d364420b3ba3fd7,37495b941da3b1661bc900e68ef3b2c6,프리스트(여),眞 크루세이더,Ocsusu,42dfa2d420111ee9854bbee20b28ea6c,꽃과뱀,[{'skillId': '7822d6d52e10964a6755f142c666b494...,[{'skillId': '5a56514f35cf0270ae8d6c65f8fefd78...

In [253]:
df[['skill.style.active', 'skill.style.passive']]

,skill.style.active,skill.style.passive
0,[{'skillId': '7822d6d52e10964a6755f142c666b494...,[{'skillId': '5a56514f35cf0270ae8d6c65f8fefd78...

In [263]:
df_skill_active = pd.DataFrame(columns=['skillId', 'name', 'level', 'requiredLevel', 'costType'])

In [265]:
for i in range(0, len(df['skill.style.active'][0])):
    print(list(df['skill.style.active'][0][i].values()))
    df_skill_active = df_skill_active.append(pd.Series(list(df['skill.style.active'][0][i].values()), index=df_skill_active.columns), ignore_index=True)

['7822d6d52e10964a6755f142c666b494', '백스텝', 1, 1, 'SP']
['3c5604bdbb0240b8f130f59ab40509c3', '라이징 슬래쉬', 1, 1, 'SP']
['c9664191611af31142e052dfaef84530', '홀리 스매쉬', 1, 1, 'SP']
['ce26c6b69d02a440a81b552bec94f03b', '퀵 스탠딩', 1, 1, 'SP']
['0969cd4054d93da07708108c0cc1c4b5', '치유의 기도', 35, 5, 'SP']
['9dda3f4a849dba1a288dd65e116860f2', '강습', 1, 5, 'SP']
['4655101518604f874721b3cc249aae10', '큐어', 1, 10, 'SP']
['eb71e1d82d92c7e1d40500a0dcd77aa6', '무기 막기', 5, 10, 'SP']
['4224f9b0b8c7c903e9a1e0f9d9f6d04d', '홀리 플래쉬', 51, 15, 'SP']
['01c3a2fb793d293a25ed8dc7a0d70c1a', '컷 인 대쉬', 1, 15, 'SP']
['ade01c1d6afc8a05055225045e89fe49', '수호의 축복', 10, 20, 'SP']
['3d8f3d438405d79f8d3ed68072674d1e', '승리의 창', 2, 20, 'SP']
['ff171dc487807bb9aa28900ca9a46b41', '세례의 빛', 46, 25, 'SP']
['547ab2b2bd860d3e37355a9cfbc1077c', '신성한 빛', 31, 25, 'SP']
['8c2379737c5acc935c1731f67f607655', '용맹의 축복', 10, 30, 'SP']
['5dc7008b12a459325b548b0715c6b73c', '세인트 월', 1, 30, 'SP']
['7e904ea3d2a9faa054604e55120a9268', '샤인 크로스', 1, 30, 'SP']
['8ee0099656df08a0b39225f8a21d514b', '홀리 써클릿', 1, 35, 'SP']
['506e7ed77d517419a6e1c437a2cedb17', '용맹의 아리아', 27, 35, 'SP']
['9bff7f2559e003766fee2853dca00631', '에디피케이션', 1, 35, 'SP']
['a6c8f69107f8c4f5d1a0c7a57d000290', '부활', 1, 40, 'SP']
['da6e37c1e3f0e8867f70007d89c239ff', '정화의 번개', 1, 40, 'SP']
['3829c15bf5f520c13998a3479ba0ce7b', '그랜드 크로스 크래쉬', 36, 45, 'SP']
['03bb5314ffd41e9458d67ef924fef38f', '재생의 아리아', 1, 45, 'SP']
['bb34e8854a93fd250347a1c64119f7ab', '크럭스 오브 빅토리아', 13, 50, 'SP']
['27bade584bb42fef68148d3a0b72bace', '리펜텐스 스매시', 22, 60, 'SP']
['04883563896fe1adac7505c6146b5f59', '대천사의 축복', 23, 70, 'SP']
['5152480fdde81362575a488d4cec4af9', '우리엘의 결계', 21, 75, 'SP']
['2391a27457b5a8c6fa4b4670a91bdd11', '미라클 샤인', 18, 80, 'SP']
['5892d1fa4462e561ac8f8d2c74892b0a', '성창 : 브류나크', 7, 85, 'SP']
['85f7c810ad503790e8626439fe936d56', '크럭스 오브 샤피엘', 11, 95, 'SP']
['002cbdd9bfd0f0b970451ae8d48d029e', '라우스 디 안젤루스', 4, 100, 'SP']

- 위 결과를 또 데이터프레임으로 만드는게 좋을 듯 하다

In [266]:
df_skill_active

                             skillId         name level requiredLevel costType
0   7822d6d52e10964a6755f142c666b494          백스텝     1             1       SP
1   3c5604bdbb0240b8f130f59ab40509c3      라이징 슬래쉬     1             1       SP
2   c9664191611af31142e052dfaef84530       홀리 스매쉬     1             1       SP
3   ce26c6b69d02a440a81b552bec94f03b        퀵 스탠딩     1             1       SP
4   0969cd4054d93da07708108c0cc1c4b5       치유의 기도    35             5       SP
5   9dda3f4a849dba1a288dd65e116860f2           강습     1             5       SP
6   4655101518604f874721b3cc249aae10           큐어     1            10       SP
7   eb71e1d82d92c7e1d40500a0dcd77aa6        무기 막기     5            10       SP
8   4224f9b0b8c7c903e9a1e0f9d9f6d04d       홀리 플래쉬    51            15       SP
9   01c3a2fb793d293a25ed8dc7a0d70c1a       컷 인 대쉬     1            15       SP
10  ade01c1d6afc8a05055225045e89fe49       수호의 축복    10            20       SP
11  3d8f3d438405d79f8d3ed68072674d1e        승리의 창     2            20       SP
12  ff171dc487807bb9aa28900ca9a46b41        세례의 빛    46            25       SP
13  547ab2b2bd860d3e37355a9cfbc1077c        신성한 빛    31            25       SP
14  8c2379737c5acc935c1731f67f607655       용맹의 축복    10            30       SP
15  5dc7008b12a459325b548b0715c6b73c        세인트 월     1            30       SP
16  7e904ea3d2a9faa054604e55120a9268       샤인 크로스     1            30       SP
17  8ee0099656df08a0b39225f8a21d514b       홀리 써클릿     1            35       SP
18  506e7ed77d517419a6e1c437a2cedb17      용맹의 아리아    27            35       SP
19  9bff7f2559e003766fee2853dca00631       에디피케이션     1            35       SP
20  a6c8f69107f8c4f5d1a0c7a57d000290           부활     1            40       SP
21  da6e37c1e3f0e8867f70007d89c239ff       정화의 번개     1            40       SP
22  3829c15bf5f520c13998a3479ba0ce7b  그랜드 크로스 크래쉬    36            45       SP
23  03bb5314ffd41e9458d67ef924fef38f      재생의 아리아     1            45       SP
24  bb34e8854a93fd250347a1c64119f7ab  크럭스 오브 빅토리아    13            50       SP
25  27bade584bb42fef68148d3a0b72bace     리펜텐스 스매시    22            60       SP
26  04883563896fe1adac7505c6146b5f59      대천사의 축복    23            70       SP
27  5152480fdde81362575a488d4cec4af9      우리엘의 결계    21            75       SP
28  2391a27457b5a8c6fa4b4670a91bdd11       미라클 샤인    18            80       SP
29  5892d1fa4462e561ac8f8d2c74892b0a    성창 : 브류나크     7            85       SP
30  85f7c810ad503790e8626439fe936d56   크럭스 오브 샤피엘    11            95       SP
31  002cbdd9bfd0f0b970451ae8d48d029e   라우스 디 안젤루스     4           100       SP

In [268]:
df_skill_passive = pd.DataFrame(columns=['skillId', 'name', 'level', 'requiredLevel', 'costType'])

In [269]:
for i in range(0, len(df['skill.style.passive'][0])):
    print(list(df['skill.style.passive'][0][i].values()))
    df_skill_passive = df_skill_passive.append(pd.Series(list(df['skill.style.passive'][0][i].values()), index=df_skill_passive.columns), ignore_index=True)

['5a56514f35cf0270ae8d6c65f8fefd78', '기본기 숙련', 110, 1, 'SP']
['892ef624d8bf3d7fc045f84825fd6104', '기초 방어구 마스터리', 1, 1, 'SP']
['12dca7fbf791e882b025a0d916181673', '컨버전', 1, 1, 'SP']
['d085127b0edd719782bd618d5688f4a1', '크루세이더의 판금 갑옷 마스터리', 1, 1, 'SP']
['8f73f243041c2d27739fe7696f02bf9b', '빛의 은총', 1, 1, 'SP']
['42c82812f86ff6704ae9952a2e6093a4', '계시 : 크루세이드', 1, 1, 'SP']
['78bd107acd474518b606be1e4fd38239', '계시 : 아리아', 34, 15, 'SP']
['9cb6f9ed646fa87f9b7680a42ce83d1a', '십자가 마스터리', 10, 20, 'SP']
['1dad88963abdc96b091fcab185a8820d', '신실한 열정', 23, 48, 'SP']
['2a0a39184de92acf1c1375e00b77404c', '고행', 1, 50, 'SP']
['1f4b87944dc5551b91bf6cd25d84b48e', '큐어 강화', 7, 50, 'TP']
['b7800c95b749062f30d466e797722589', '치유의 기도 강화', 7, 50, 'TP']
['0c262dac3ec41ff79e359ada9c7a7faf', '무기 막기 강화', 7, 50, 'TP']
['734356e3ab223ae24904d8ce7fa6de17', '홀리 플래쉬 강화', 3, 50, 'TP']
['b306cc4c67c775ab7ddff9785a3fe6a4', '용맹의 아리아 강화', 5, 55, 'TP']
['4f81796bde5a92136ce689da70b5e393', '신성한 빛 강화', 7, 55, 'TP']
['2b39a776471c142f581ad3cc8bb89e55', '정화의 번개 강화', 5, 55, 'TP']
['1c1a9606eb702ebe5a7bb4397f3aeae0', '대천사의 축복 강화', 5, 70, 'TP']
['dbf8b30c7057032af0d68fcfa289fdae', '라파엘의 축복', 14, 75, 'SP']
['5cac3411ccef1af333953e0ded5e942d', '루클렌티스 엔젤', 7, 95, 'SP']

In [270]:
df_skill_passive

,skillId,name,level,requiredLevel,costType
0,5a56514f35cf0270ae8d6c65f8fefd78,기본기 숙련,110,1,SP
1,892ef624d8bf3d7fc045f84825fd6104,기초 방어구 마스터리,1,1,SP
2,12dca7fbf791e882b025a0d916181673,컨버전,1,1,SP
3,d085127b0edd719782bd618d5688f4a1,크루세이더의 판금 갑옷 마스터리,1,1,SP
4,8f73f243041c2d27739fe7696f02bf9b,빛의 은총,1,1,SP
5,42c82812f86ff6704ae9952a2e6093a4,계시 : 크루세이드,1,1,SP
6,78bd107acd474518b606be1e4fd38239,계시 : 아리아,34,15,SP
7,9cb6f9ed646fa87f9b7680a42ce83d1a,십자가 마스터리,10,20,SP
8,1dad88963abdc96b091fcab185a8820d,신실한 열정,23,48,SP
9,2a0a39184de92acf1c1375e00b77404c,고행,1,50,SP
10,1f4b87944dc5551b91bf6cd25d84b48e,큐어 강화,7,50,TP
11,b7800c95b749062f30d466e797722589,치유의 기도 강화,7,50,TP
12,0c262dac3ec41ff79e359ada9c7a7faf,무기 막기 강화,7,50,TP
13,734356e3ab223ae24904d8ce7fa6de17,홀리 플래쉬 강화,3,50,TP
14,b306cc4c67c775ab7ddff9785a3fe6a4,용맹의 아리아 강화,5,55,TP
15,4f81796bde5a92136ce689da70b5e393,신성한 빛 강화,7,55,TP
16,2b39a776471c142f581ad3cc8bb89e55,정화의 번개 강화,5,55,TP
17,1c1a9606eb702ebe5a7bb4397f3aeae0,대천사의 축복 강화,5,70,TP
18,dbf8b30c7057032af0d68fcfa289fdae,라파엘의 축복,14,75,SP
19,5cac3411ccef1af333953e0ded5e942d,루클렌티스 엔젤,7,95,SP

## 12. 캐릭터 버프 스킬 강화 장착 장비 조회

In [271]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/skill/buff/equip/equipment?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [272]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [273]:
df = json_normalize(json_ob)

In [274]:
df

,characterId,characterName,level,jobId,jobGrowId,jobName,jobGrowName,adventureName,guildId,guildName,skill.buff.skillInfo.skillId,skill.buff.skillInfo.name,skill.buff.skillInfo.option.level,skill.buff.skillInfo.option.desc,skill.buff.skillInfo.option.values,skill.buff.equipment
0,ad34d7a0b8c7267b8f921c79e57ddebd,노블레스,110,0c1b401bb09241570d364420b3ba3fd7,37495b941da3b1661bc900e68ef3b2c6,프리스트(여),眞 크루세이더,Ocsusu,42dfa2d420111ee9854bbee20b28ea6c,꽃과뱀,8c2379737c5acc935c1731f67f607655,용맹의 축복,16,버프 적용 범위 : {value1}px\n지속시간 : {value2}초\n물리 공격...,"[900, 120, 62, 62, 62, 370, 370, 28.4, 58]","[{'slotId': 'TITLE', 'slotName': '칭호', 'itemId..."

In [280]:
df.iloc[:, 10:]

,skill.buff.skillInfo.skillId,skill.buff.skillInfo.name,skill.buff.skillInfo.option.level,skill.buff.skillInfo.option.desc,skill.buff.skillInfo.option.values,skill.buff.equipment
0,8c2379737c5acc935c1731f67f607655,용맹의 축복,16,버프 적용 범위 : {value1}px\n지속시간 : {value2}초\n물리 공격...,"[900, 120, 62, 62, 62, 370, 370, 28.4, 58]","[{'slotId': 'TITLE', 'slotName': '칭호', 'itemId..."

### 버프 장비가 16레벨 일 때의 파워 (option.desc, option.values)

In [299]:
opt_desc = list(filter(None, df['skill.buff.skillInfo.option.desc'][0].split('\n'))) # 공백제거
opt_desc

['버프 적용 범위 : {value1}px',
 '지속시간 : {value2}초',
 '물리 공격력 증가량 : {value3}',
 '마법 공격력 증가량 : {value4}',
 '독립 공격력 증가량 : {value5}',
 '힘 증가량 : {value6}',
 '지능 증가량 : {value7}',
 '적중률 증가량 : {value8}%',
 '기본 공격 및 스킬 공격력 증가량 : {value9}%']

In [301]:
opt_val = df['skill.buff.skillInfo.option.values'][0]
opt_val

['900', '120', '62', '62', '62', '370', '370', '28.4', '58']

### -> desc와 values를 짝지어주면 되겠군용
- value 자리에 맞는 수를 집어 넣어 줍니다 (지금은 보기 편하게 아래처럼 처리했지만, 나중엔 동일한 컬럼명에 숫자만 적재해서 데이터프레임 만들면 될 듯)

In [306]:
for i in range(0, len(opt_val)):
    print(opt_desc[i].replace('value{0}'.format(i+1), opt_val[i]))

버프 적용 범위 : {900}px
지속시간 : {120}초
물리 공격력 증가량 : {62}
마법 공격력 증가량 : {62}
독립 공격력 증가량 : {62}
힘 증가량 : {370}
지능 증가량 : {370}
적중률 증가량 : {28.4}%
기본 공격 및 스킬 공격력 증가량 : {58}%

## 13. 캐릭터 '버프 스킬 강화 장착 아바타' 조회

In [307]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/skill/buff/equip/avatar?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [308]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [309]:
df = json_normalize(json_ob)

In [310]:
df

,characterId,characterName,level,jobId,jobGrowId,jobName,jobGrowName,adventureName,guildId,guildName,skill.buff.skillInfo.skillId,skill.buff.skillInfo.name,skill.buff.skillInfo.option.level,skill.buff.skillInfo.option.desc,skill.buff.skillInfo.option.values,skill.buff.avatar
0,ad34d7a0b8c7267b8f921c79e57ddebd,노블레스,110,0c1b401bb09241570d364420b3ba3fd7,37495b941da3b1661bc900e68ef3b2c6,프리스트(여),眞 크루세이더,Ocsusu,42dfa2d420111ee9854bbee20b28ea6c,꽃과뱀,8c2379737c5acc935c1731f67f607655,용맹의 축복,16,버프 적용 범위 : {value1}px\n지속시간 : {value2}초\n물리 공격...,"[900, 120, 62, 62, 62, 370, 370, 28.4, 58]","[{'slotId': 'PANTS', 'slotName': '하의 아바타', 'it..."

#### 위 결과에서 skill.buff.avatar 변수만 추가

In [314]:
pd.DataFrame(df['skill.buff.avatar'][0][0])

,slotId,slotName,itemId,itemName,itemRarity,cloneAvatarName,optionAbility,emblems
0,PANTS,하의 아바타,0fa49082a4ba6edb07b93f7210965391,여명의 천신 예복 하의,레어,None,HP MAX 400 증가,"{'slotNo': 1, 'slotColor': '플래티넘', 'itemName':..."

In [316]:
df['skill.buff.avatar'][0][0]['emblems'] # 버프 장착

[{'slotNo': 1,
  'slotColor': '플래티넘',
  'itemName': '플래티넘 엠블렘[용맹의 축복]',
  'itemRarity': '레전더리'}]

In [317]:
pd.DataFrame(df['skill.buff.avatar'][0][1])

,slotId,slotName,itemId,itemName,itemRarity,cloneAvatarName,optionAbility,emblems
0,JACKET,상의 아바타,e43347701f6cfe7f4a30402052b8dc9e,칠흑의 천신 예복 상의,레어,None,용맹의 축복 스킬Lv +1,"{'slotNo': 1, 'slotColor': '플래티넘', 'itemName':..."

### -> 오 레압

In [318]:
df['skill.buff.avatar'][0][1]['emblems']

[{'slotNo': 1,
  'slotColor': '플래티넘',
  'itemName': '플래티넘 엠블렘[용맹의 축복]',
  'itemRarity': '레전더리'}]

## 14. 캐릭터 '버프 스킬 강화 장착 크리처' 조회

In [319]:
url = 'https://api.neople.co.kr/df/servers/cain/characters/ad34d7a0b8c7267b8f921c79e57ddebd/skill/buff/equip/creature?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [320]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [321]:
df = json_normalize(json_ob)

In [322]:
df

,characterId,characterName,level,jobId,jobGrowId,jobName,jobGrowName,adventureName,guildId,guildName,skill.buff.skillInfo.skillId,skill.buff.skillInfo.name,skill.buff.skillInfo.option.level,skill.buff.skillInfo.option.desc,skill.buff.skillInfo.option.values,skill.buff.creature
0,ad34d7a0b8c7267b8f921c79e57ddebd,노블레스,110,0c1b401bb09241570d364420b3ba3fd7,37495b941da3b1661bc900e68ef3b2c6,프리스트(여),眞 크루세이더,Ocsusu,42dfa2d420111ee9854bbee20b28ea6c,꽃과뱀,8c2379737c5acc935c1731f67f607655,용맹의 축복,16,버프 적용 범위 : {value1}px\n지속시간 : {value2}초\n물리 공격...,"[900, 120, 62, 62, 62, 370, 370, 28.4, 58]",[{'itemId': 'f5c87c63bbdaa5413a105640cafbc30a'...

In [324]:
df['skill.buff.creature'][0]

[{'itemId': 'f5c87c63bbdaa5413a105640cafbc30a',
  'itemName': '순백의 나비 공주',
  'itemRarity': '레어',
  'enchant': None}]

## 15. 경매장 등록 아이템 검색
- '진정한 각성을 이룬 자'로 test

In [325]:
url = 'https://api.neople.co.kr/df/auction?itemId=c89a01593a155a3cbaaf272084d8fb57&itemName=%ec%a7%84%ec%a0%95%ed%95%9c+%ea%b0%81%ec%84%b1%ec%9d%84+%ec%9d%b4%eb%a3%ac+%ec%9e%90&limit=<limit>&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [326]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [331]:
df = pd.DataFrame(json_ob)

In [353]:
df_auc = pd.DataFrame(columns=df.iloc[0][0].keys())

In [354]:
for i in range(0, len(df)):
    df_auc = df_auc.append(pd.Series(list(df.iloc[i][0].values()), index=df_auc.columns), ignore_index=True)

In [355]:
df_auc

,auctionNo,regDate,expireDate,itemId,itemName,itemAvailableLevel,itemRarity,itemTypeId,itemType,itemTypeDetailId,itemTypeDetail,refine,reinforce,amplificationName,adventureFame,count,price,currentPrice,unitPrice,averagePrice
0,1232830052,2023-03-28 22:47:04,2023-03-29 22:47:04,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,32400000,32400000,0
1,1232831512,2023-03-28 22:52:45,2023-03-29 22:52:45,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,32400000,32400000,0
2,1232841777,2023-03-28 23:34:32,2023-03-29 23:34:32,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,32000000,32000000,0
3,1232844169,2023-03-28 23:45:28,2023-03-29 23:45:28,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,31000000,31000000,0
4,1232844197,2023-03-28 23:45:34,2023-03-29 23:45:34,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,31000000,31000000,0
5,1232862198,2023-03-29 01:29:00,2023-03-30 01:29:00,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,32999848,32999848,0
6,1232867729,2023-03-29 02:16:53,2023-03-30 02:16:53,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,30100000,30100000,0
7,1232881502,2023-03-29 06:25:12,2023-03-30 06:25:12,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,980,1,-1,29980000,29980000,0
8,1232881515,2023-03-29 06:25:24,2023-03-30 06:25:24,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,980,1,-1,29980000,29980000,0
9,1232881765,2023-03-29 06:32:48,2023-03-30 06:32:48,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1005,1,-1,33000000,33000000,0

## 16. 경매장 등록 아이템 조회

In [360]:
url = 'https://api.neople.co.kr/df/auction/1232881502?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [361]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [367]:
pd.DataFrame.from_records([json_ob])

,auctionNo,regDate,expireDate,itemId,itemName,itemAvailableLevel,itemRarity,itemTypeId,itemType,itemTypeDetailId,itemTypeDetail,refine,reinforce,amplificationName,adventureFame,count,price,currentPrice,unitPrice,averagePrice
0,1232881502,2023-03-29 06:25:12,2023-03-30 06:25:12,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,980,1,-1,29980000,29980000,0

## 17. 경매장 시세 검색

In [368]:
url = 'https://api.neople.co.kr/df/auction-sold?itemId=c89a01593a155a3cbaaf272084d8fb57&itemName=%ec%a7%84%ec%a0%95%ed%95%9c+%ea%b0%81%ec%84%b1%ec%9d%84+%ec%9d%b4%eb%a3%ac+%ec%9e%90&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [369]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [376]:
df_auc_sold = pd.DataFrame(columns=json_ob['rows'][0].keys())

for i in range(0, len(json_ob['rows'])):
    df_auc_sold = df_auc_sold.append(pd.Series(list(json_ob['rows'][i].values()), index=df_auc_sold.columns), ignore_index=True)

In [377]:
df_auc_sold

,soldDate,itemId,itemName,itemAvailableLevel,itemRarity,itemTypeId,itemType,itemTypeDetailId,itemTypeDetail,refine,reinforce,amplificationName,count,price,unitPrice
0,2023-03-29 22:51:54,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,25300000,25300000
1,2023-03-29 22:51:39,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,24900000,24900000
2,2023-03-29 22:50:58,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,25599999,25599999
3,2023-03-29 22:50:52,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,25589999,25589999
4,2023-03-29 22:50:48,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,25400000,25400000
5,2023-03-29 22:50:43,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,25500000,25500000
6,2023-03-29 22:50:35,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,29890000,29890000
7,2023-03-29 22:50:07,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,26700000,26700000
8,2023-03-29 22:49:50,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,29499999,29499999
9,2023-03-29 22:49:46,c89a01593a155a3cbaaf272084d8fb57,진정한 각성을 이룬 자,1,레어,e490f8cce6bacd43bef1e2f5e0c4943d,액세서리,691933a06ff114348a7db936fb0aec66,칭호,0,0,None,1,25590000,25590000

### Q. 시세가 날짜 기준으로 어떻게 가격 변동이 일어났는가

## 18. 아바타 마켓 상품 검색

In [381]:
url = 'https://api.neople.co.kr/df/avatar-market/sale?&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

- 파라미터에 값 넣을게 아니라면 해당 부분 url에서 지워주기

In [382]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [386]:
df = json_normalize(json_ob['rows'])

In [390]:
df['avatar'][0][0].values()

dict_values(['HEADGEAR', '모자 아바타', '8d89bd9b3f5f6676c5c5d2352bffa31b', '진 메카닉의 강화형 롤링썬더[B타입]', '커먼', '지능 45 증가', []])

In [416]:
df

,goodsNo,title,price,jobId,jobName,soldDate,hashtag,avatarSet,avatarRarity,avatarCount,avatar,emblem.code,emblem.name
0,2987580,여거너 상급2부위,2700000,944b9aab492c15a8474f96947ceeb9e4,거너(여),None,[],False,상급,2,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
1,2985343,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
2,2985339,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
3,2985358,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'FACE', 'slotName': '얼굴 아바타', 'ite...",100,없음
4,2985351,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'FACE', 'slotName': '얼굴 아바타', 'ite...",100,없음
5,2985356,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'FACE', 'slotName': '얼굴 아바타', 'ite...",100,없음
6,2985341,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'BREAST', 'slotName': '목가슴 아바타', '...",100,없음
7,2985344,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
8,2985355,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'FACE', 'slotName': '얼굴 아바타', 'ite...",100,없음
9,2985345,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음

In [436]:
df['avatar'][0]

[{'slotId': 'HEADGEAR',
  'slotName': '모자 아바타',
  'itemId': '8d89bd9b3f5f6676c5c5d2352bffa31b',
  'itemName': '진 메카닉의 강화형 롤링썬더[B타입]',
  'itemRarity': '커먼',
  'optionAbility': '지능 45 증가',
  'emblems': []},
 {'slotId': 'WAIST',
  'slotName': '허리 아바타',
  'itemId': '395c6e31cc84e413f507e7d25be9ab21',
  'itemName': '진 메카닉의 노리개 벨트[B타입]',
  'itemRarity': '커먼',
  'optionAbility': '회피율 4.0% 증가',
  'emblems': []}]

In [418]:
df.iloc[0]['goodsNo']

2987580

In [423]:
all_list_gn = []
all_list = []
for i in range(0, len(df['avatar'])):
    for j in range(0, len(df['avatar'][0])):
        all_list.append(list(df['avatar'][i][j].values()))
        all_list_gn.append(df.iloc[i]['goodsNo'])

In [433]:
df_avatar_market = pd.DataFrame(all_list).merge(pd.DataFrame(all_list_gn), left_index=True, right_index=True)

In [439]:
df_avatar_market

,0_x,1,2,3,4,5,6,0_y
0,HEADGEAR,모자 아바타,8d89bd9b3f5f6676c5c5d2352bffa31b,진 메카닉의 강화형 롤링썬더[B타입],커먼,지능 45 증가,[],2987580
1,WAIST,허리 아바타,395c6e31cc84e413f507e7d25be9ab21,진 메카닉의 노리개 벨트[B타입],커먼,회피율 4.0% 증가,[],2987580
2,HEADGEAR,모자 아바타,63b8ecd48783be23f0af6a354de9e712,판타지 코스프레 실버블루 머리 장신구[D타입],커먼,정신력 45 증가,[],2985343
3,SHOES,신발 아바타,1492e429d3cc7014990f1b6864c7a4d7,판타지 코스프레 블루 아머 슈즈[D타입],커먼,힘 45 증가,[],2985343
4,HEADGEAR,모자 아바타,b86a4c506ac5d21fbab6b488f53fab0b,판타지 코스프레 브론즈 머리 장신구[A타입],커먼,캐스팅 속도 12.0% 증가,[],2985339
5,SHOES,신발 아바타,4e3f0184a6009c00948dbbb6d36d1475,판타지 코스프레 블랙 아머 슈즈[A타입],커먼,힘 45 증가,[],2985339
6,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985358
7,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985358
8,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985351
9,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985351
10,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985356
11,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985356
12,BREAST,목가슴 아바타,9b1527b99c714eed5b954f84c9664aaf,판타지 코스프레 블루 숄더 아머[D타입],커먼,공격 속도 5.0% 증가,[],2985341
13,WAIST,허리 아바타,2bc6146c91c137cad4d2ae7afa05c777,판타지 코스프레 블루 엔틱 단검[D타입],커먼,회피율 4.0% 증가,[],2985341
14,HEADGEAR,모자 아바타,63b8ecd48783be23f0af6a354de9e712,판타지 코스프레 실버블루 머리 장신구[D타입],커먼,지능 45 증가,[],2985344
15,HAIR,머리 아바타,e9e76b8a729f0dcb104341a8587bbd90,판타지 코스프레 레드 내추럴 헤어[A타입],커먼,캐스팅 속도 12.0% 증가,[],2985344
16,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985355
17,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985355
18,HEADGEAR,모자 아바타,63b8ecd48783be23f0af6a354de9e712,판타지 코스프레 실버블루 머리 장신구[D타입],커먼,캐스팅 속도 12.0% 증가,[],2985345
19,SHOES,신발 아바타,1492e429d3cc7014990f1b6864c7a4d7,판타지 코스프레 블루 아머 슈즈[D타입],커먼,이동 속도 5.0% 증가,[],2985345

In [440]:
df_avatar_market.columns = ['slotId', 'slotName', 'itemId', 'itemName', 'itemRarity', 'optionAbility', 'emblems', 'goodsNo']

In [441]:
df_avatar_market

,slotId,slotName,itemId,itemName,itemRarity,optionAbility,emblems,goodsNo
0,HEADGEAR,모자 아바타,8d89bd9b3f5f6676c5c5d2352bffa31b,진 메카닉의 강화형 롤링썬더[B타입],커먼,지능 45 증가,[],2987580
1,WAIST,허리 아바타,395c6e31cc84e413f507e7d25be9ab21,진 메카닉의 노리개 벨트[B타입],커먼,회피율 4.0% 증가,[],2987580
2,HEADGEAR,모자 아바타,63b8ecd48783be23f0af6a354de9e712,판타지 코스프레 실버블루 머리 장신구[D타입],커먼,정신력 45 증가,[],2985343
3,SHOES,신발 아바타,1492e429d3cc7014990f1b6864c7a4d7,판타지 코스프레 블루 아머 슈즈[D타입],커먼,힘 45 증가,[],2985343
4,HEADGEAR,모자 아바타,b86a4c506ac5d21fbab6b488f53fab0b,판타지 코스프레 브론즈 머리 장신구[A타입],커먼,캐스팅 속도 12.0% 증가,[],2985339
5,SHOES,신발 아바타,4e3f0184a6009c00948dbbb6d36d1475,판타지 코스프레 블랙 아머 슈즈[A타입],커먼,힘 45 증가,[],2985339
6,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985358
7,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985358
8,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985351
9,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985351
10,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985356
11,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985356
12,BREAST,목가슴 아바타,9b1527b99c714eed5b954f84c9664aaf,판타지 코스프레 블루 숄더 아머[D타입],커먼,공격 속도 5.0% 증가,[],2985341
13,WAIST,허리 아바타,2bc6146c91c137cad4d2ae7afa05c777,판타지 코스프레 블루 엔틱 단검[D타입],커먼,회피율 4.0% 증가,[],2985341
14,HEADGEAR,모자 아바타,63b8ecd48783be23f0af6a354de9e712,판타지 코스프레 실버블루 머리 장신구[D타입],커먼,지능 45 증가,[],2985344
15,HAIR,머리 아바타,e9e76b8a729f0dcb104341a8587bbd90,판타지 코스프레 레드 내추럴 헤어[A타입],커먼,캐스팅 속도 12.0% 증가,[],2985344
16,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],커먼,공격 속도 5.0% 증가,[],2985355
17,BREAST,목가슴 아바타,0061955ee9bd6a1a7b17e3504fbc17c9,차원 여행자의 시공 포털 GN-A08[A타입],커먼,공격 속도 5.0% 증가,[],2985355
18,HEADGEAR,모자 아바타,63b8ecd48783be23f0af6a354de9e712,판타지 코스프레 실버블루 머리 장신구[D타입],커먼,캐스팅 속도 12.0% 증가,[],2985345
19,SHOES,신발 아바타,1492e429d3cc7014990f1b6864c7a4d7,판타지 코스프레 블루 아머 슈즈[D타입],커먼,이동 속도 5.0% 증가,[],2985345

## 19. 아바타 마켓 상품 조회

In [442]:
url = 'https://api.neople.co.kr/df/avatar-market/sale/2985343?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [443]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [448]:
df = json_normalize(json_ob)

In [449]:
df

,goodsNo,title,price,jobId,jobName,soldDate,hashtag,avatarSet,avatarRarity,avatarCount,avatar,emblem.code,emblem.name
0,2985343,남거너 상급2부위,2790000,afdf3b989339de478e85b614d274d1ef,거너(남),None,[],False,상급,2,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음

In [452]:
pd.DataFrame(df['avatar'][0])

,slotId,slotName,itemId,itemName,itemRarity,optionAbility,emblems
0,HEADGEAR,모자 아바타,63b8ecd48783be23f0af6a354de9e712,판타지 코스프레 실버블루 머리 장신구[D타입],커먼,정신력 45 증가,[]
1,SHOES,신발 아바타,1492e429d3cc7014990f1b6864c7a4d7,판타지 코스프레 블루 아머 슈즈[D타입],커먼,힘 45 증가,[]

## 20. 아바타 마켓 상품 시세 검색
- hashtag 정보는 "아바타 마켓 해시태그 조회 API"를 통해서 확인 가능합니다.

In [453]:
url = 'https://api.neople.co.kr/df/avatar-market/sold?&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [454]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [458]:
df = json_normalize(json_ob['rows'])
df

,goodsNo,title,price,jobId,jobName,soldDate,hashtag,avatarSet,avatarRarity,avatarCount,avatar,emblem.code,emblem.name
0,2956177,나이트 11차 레어 세트[A타입],6500,0ee8fa5dc525c1a1f23fc6911e921e4a,나이트,2023-03-11,[],True,레어,8,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",130,찬란한
1,2943116,남귀검사 14 야생의 사파리 세트[A타입],820000,41f1cdc2ff58bb5fdc287be0db2a8df3,귀검사(남),2023-03-04,[동물],True,상급,6,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
2,2939472,여마법사 22 포레스트 엘프 세트[B타입],1050000,3909d0b188e9c95311399f776e331da5,마법사(여),2023-03-02,[],True,상급,8,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
3,2973403,여귀검사 18 아시아 여행 일본 세트[D타입],1100000,1645c45aabb008c98406b3a16447040d,귀검사(여),2023-03-22,[],True,상급,8,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
4,2978936,마창사 21 고양이 킹덤 세트[D타입],1100000,3deb7be5f01953ac8b1ecaa1e25e0420,마창사,2023-03-25,[],True,상급,8,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
5,2961162,여귀검사 상급3부위/피부,1100000,1645c45aabb008c98406b3a16447040d,귀검사(여),2023-03-14,[],False,상급,4,"[{'slotId': 'HAIR', 'slotName': '머리 아바타', 'ite...",100,없음
6,2966732,여마법사 진각성의서 마도학자 세트[A타입],1150000,3909d0b188e9c95311399f776e331da5,마법사(여),2023-03-18,[],True,상급,9,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음
7,2931823,여거너 각성의 서 프레이야 세트[A타입],1180000,944b9aab492c15a8474f96947ceeb9e4,거너(여),2023-02-27,[],True,상급,9,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",110,빛나는
8,2933569,여귀검사 18 아시아 여행 일본 세트[D타입],1190000,1645c45aabb008c98406b3a16447040d,귀검사(여),2023-02-27,[],True,상급,8,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",110,빛나는
9,2962711,남귀검사 22 룡방신기 세트[D타입],1198550,41f1cdc2ff58bb5fdc287be0db2a8df3,귀검사(남),2023-03-15,[],True,상급,8,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음

In [461]:
pd.DataFrame(df['avatar'][0]) # 나이트 11차 레어 세트[A타입]의 구성요소

,slotId,slotName,itemId,itemName,itemRarity,optionAbility,emblems
0,HEADGEAR,모자 아바타,b00166576f8aa6cbb22ce0916868599e,플레이아데스 장미 코사지,레어,지능 55 증가,"[{'slotNo': 1, 'slotColor': '붉은빛', 'itemName':..."
1,HAIR,머리 아바타,825df4c14bcfca4097e36734da3317e3,플레이아데스 웨이브 포니테일,레어,지능 55 증가,"[{'slotNo': 1, 'slotColor': '붉은빛', 'itemName':..."
2,FACE,얼굴 아바타,ce5affe1c1c30f7355382c199505525c,플레이아데스 깃털 귀걸이,레어,공격 속도 6.0% 증가,"[{'slotNo': 1, 'slotColor': '노란빛', 'itemName':..."
3,JACKET,상의 아바타,925014e18f1cf48f05071e7b384fd2a9,플레이아데스 상의,레어,브레인 스톰 스킬Lv +1,"[{'slotNo': 1, 'slotColor': '플래티넘', 'itemName'..."
4,PANTS,하의 아바타,06e00b38e97bcb44bfa30df5c8050a21,플레이아데스 프릴 스커트,레어,MP MAX 400 증가,"[{'slotNo': 1, 'slotColor': '플래티넘', 'itemName'..."
5,SHOES,신발 아바타,dd9a4831b44f05ae845cf974796c7c17,플레이아데스 부츠,레어,이동 속도 6.0% 증가,"[{'slotNo': 1, 'slotColor': '푸른빛', 'itemName':..."
6,BREAST,목가슴 아바타,ba813dcff64875bcb294f075e0375b65,플레이아데스 원석 초커,레어,공격 속도 6.0% 증가,"[{'slotNo': 1, 'slotColor': '노란빛', 'itemName':..."
7,WAIST,허리 아바타,65b7c5e99fc9263b65ddb984990089da,플레이아데스 장미 벨트,레어,회피율 5.5% 증가,"[{'slotNo': 1, 'slotColor': '푸른빛', 'itemName':..."

## 21. 아바타 마켓 상품 시세 조회

In [488]:
url = 'https://api.neople.co.kr/df/avatar-market/sold/2978936?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25' #  goodsNo 제거하고 실행도 가능

In [489]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [491]:
json_normalize(json_ob)

,goodsNo,title,price,jobId,jobName,soldDate,hashtag,avatarSet,avatarRarity,avatarCount,avatar,emblem.code,emblem.name
0,2978936,마창사 21 고양이 킹덤 세트[D타입],1100000,3deb7be5f01953ac8b1ecaa1e25e0420,마창사,2023-03-25,[],True,상급,8,"[{'slotId': 'HEADGEAR', 'slotName': '모자 아바타', ...",100,없음

## 22. 아바타 마켓 해시태그 조회

In [501]:
url = 'https://api.neople.co.kr/df/avatar-market/hashtag?&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [502]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [507]:
pd.DataFrame(pd.Series(json_ob['rows']))

        0
0      SF
1     강인한
2      개그
3      공포
4     공허한
5     귀여움
6     깔끔한
7     냉정한
8      동물
9     드라마
10     만화
11    몬스터
12    발랄한
13    배고픔
14    분노한
15  사랑스러운
16     서양
17    세련된
18     섹시
19    시크한
20    아시아
21     악당
22     악마
23     영웅
24     영화
25  온라인게임
26    우아함
27    우울한
28    자신감
29     자연
30     전사
31     전설
32     제복
33     중세
34     천사
35     청순
36   충격적인
37    특이한
38    판타지
39    평범한
40     흔한
41    희귀한

## 23. 아이템 검색 ****

In [526]:
url = 'https://api.neople.co.kr/df/items?&hashtag=%ea%b3%b5%ed%8f%ac&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [527]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [528]:
json_ob

{'rows': []}

## 24. 아이템 상세 정보 조회

In [529]:
url = 'https://api.neople.co.kr/df/items/8d89bd9b3f5f6676c5c5d2352bffa31b?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [530]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [532]:
json_normalize(json_ob)

,itemId,itemName,itemRarity,itemTypeId,itemType,itemTypeDetailId,itemTypeDetail,itemAvailableLevel,itemObtainInfo,itemExplain,itemExplainDetail,itemFlavorText,setItemId,setItemName
0,8d89bd9b3f5f6676c5c5d2352bffa31b,진 메카닉의 강화형 롤링썬더[B타입],커먼,5f41b95e310c27783378edde2d24c3dd,아바타,39815fc766534091463f2a6b025d370e,모자,1,* 경매장에서 획득,<진 각성의 서>,<진 각성의 서>,,6e08117170a677f8849a71c74411a4cf,진 각성의 서 아바타 세트

## 25. 아이템 상점 판매 정보 조회
- 인게임 백과사전 기준의 상점 판매 95레벨 에픽, 100레벨 이상 유니크, 레전더리, 에픽 장비가 조회 가능 합니다.

In [533]:
url = 'https://api.neople.co.kr/df/items/8d89bd9b3f5f6676c5c5d2352bffa31b/shop?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [534]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [535]:
json_ob

{'error': {'status': 404, 'code': 'DNF003', 'message': 'NOT_FOUND_ITEM'}}

## 26. 다중 아이템 상세 정보 조회

In [546]:
url = 'https://api.neople.co.kr/df/multi/items?itemIds=b00166576f8aa6cbb22ce0916868599e,ce5affe1c1c30f7355382c199505525c,65b7c5e99fc9263b65ddb984990089da&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [547]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [548]:
json_normalize(json_ob['rows'])

,itemId,itemName,itemRarity,itemTypeId,itemType,itemTypeDetailId,itemTypeDetail,itemAvailableLevel,itemObtainInfo,itemExplain,itemExplainDetail,itemFlavorText,setItemId,setItemName
0,b00166576f8aa6cbb22ce0916868599e,플레이아데스 장미 코사지,레어,5f41b95e310c27783378edde2d24c3dd,아바타,39815fc766534091463f2a6b025d370e,모자,1,* 경매장에서 획득,,,,be471bcc556f0c5f8b16c05f6eab1100,레어 아바타 세트
1,ce5affe1c1c30f7355382c199505525c,플레이아데스 깃털 귀걸이,레어,5f41b95e310c27783378edde2d24c3dd,아바타,d4722756a5a43ce7a87f5d7cb703df74,얼굴,1,* 경매장에서 획득,,,,be471bcc556f0c5f8b16c05f6eab1100,레어 아바타 세트
2,65b7c5e99fc9263b65ddb984990089da,플레이아데스 장미 벨트,레어,5f41b95e310c27783378edde2d24c3dd,아바타,5053aacc8fe4e6dd3d9da9196da61261,허리,1,* 경매장에서 획득,,,,be471bcc556f0c5f8b16c05f6eab1100,레어 아바타 세트

## 27. 아이템 해시태그

In [549]:
url = 'https://api.neople.co.kr/df/item-hashtag?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [550]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [557]:
pd.DataFrame(pd.Series(json_ob['rows']))

                0
0          HP MAX
1           HP 소모
2           HP 조건
3           HP 회복
4          MP MAX
..            ...
123   석화 버프 조합 장비
124  기본기 스킬 조합 장비
125         세트 장비
126        근위대 세트
127      속성 강화 조건

[128 rows x 1 columns]

## 28. 세트 아이템 검색

In [567]:
url = 'https://api.neople.co.kr/df/setitems?setItemName=%ec%82%bc%ec%bc%9c%ec%a7%84+%eb%b6%84%eb%85%b8+%ec%84%b8%ed%8a%b8&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [568]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [571]:
json_normalize(json_ob['rows'])

                          setItemId setItemName
0  ae4e5f8c339b667f2af12db2505f6ece   삼켜진 분노 세트

## 29. 세트 아이템 상세 정보 조회

In [572]:
url = 'https://api.neople.co.kr/df/setitems/ae4e5f8c339b667f2af12db2505f6ece?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [573]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [575]:
json_normalize(json_ob)

,setItemId,setItemName,setItems,setItemOption
0,ae4e5f8c339b667f2af12db2505f6ece,삼켜진 분노 세트,"[{'slotId': 'JACKET', 'slotName': '상의', 'itemI...","[{'optionNo': 2, 'explain': '스킬 공격력 2.5% 증가 공..."

In [577]:
pd.DataFrame(json_ob['setItems']) # 세트아이템의 구성요소

    slotId slotName                            itemId    itemName itemRarity
0   JACKET       상의  8f833c773b16a1236d31a0c6a3f09cff  세상을 삼키는 분노         신화
1   JACKET       상의  2f15190f0615de75cf4cdae922e70bc9    피를 머금은 한         에픽
2   AMULET      목걸이  880219804acccc7d1deff35843742c31  과격한 분노의 격앙         에픽
3  SUPPORT     보조장비  d5aa285ea041ca244da5c0d6103ac8f8  통제할 수 없는 화         에픽

In [589]:
setitem_opt = pd.DataFrame(json_ob['setItemOption']) # 상세 효과?
setitem_opt

,optionNo,explain,detailExplain,itemBuff
0,2,스킬 공격력 2.5% 증가\n\n공격 시 30초동안 광기 버프 발생,"스킬 공격력 2.5% 증가\n\n공격 시 30초동안 광기 버프 발생 (쿨타임 5초,...","{'explain': '버프력 125 슬로우 힐, 치유의 기도, 꼼꼼한 바느질, ..."
1,3,스킬 공격력 1% 증가n\n피격 시 받는 데미지 10% 증가\n\n스킬 및 포션으로...,스킬 공격력 1% 증가\n\n피격 시 받는 데미지 10% 증가\n\n스킬 및 포션으...,{'explain': '버프력 175 자신을 제외한 파티원이 받는 회복 스킬 효과...

In [601]:
for i in range(0, len(pd.DataFrame(json_ob['setItemOption']))):
    setitem_opt['explain'][i] = setitem_opt['explain'][i].replace('\n', '')
    setitem_opt['detailExplain'][i] = setitem_opt['detailExplain'][i].replace('\n', '')
    setitem_opt['itemBuff'][i] = setitem_opt['itemBuff'][i]['explain'].replace('\n', '')

In [602]:
setitem_opt

,optionNo,explain,detailExplain,itemBuff
0,2,스킬 공격력 2.5% 증가공격 시 30초동안 광기 버프 발생,"스킬 공격력 2.5% 증가공격 시 30초동안 광기 버프 발생 (쿨타임 5초, 최대 ...","버프력 125슬로우 힐, 치유의 기도, 꼼꼼한 바느질, 밤과 꿈 시전 시 450px..."
1,3,스킬 공격력 1% 증가n피격 시 받는 데미지 10% 증가스킬 및 포션으로 인한 HP...,스킬 공격력 1% 증가피격 시 받는 데미지 10% 증가스킬 및 포션으로 인한 HP ...,버프력 175자신을 제외한 파티원이 받는 회복 스킬 효과 10% 증가보스 몬스터 2...

## 30. 다중 세트 아이템 상세 정보 조회

In [623]:
url = 'https://api.neople.co.kr/df/multi/setitems?setItemIds=ae4e5f8c339b667f2af12db2505f6ece&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [624]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [625]:
json_normalize(json_ob['rows'])

,setItemId,setItemName,setItems,setItemOption
0,ae4e5f8c339b667f2af12db2505f6ece,삼켜진 분노 세트,"[{'slotId': 'JACKET', 'slotName': '상의', 'itemI...","[{'optionNo': 2, 'explain': '스킬 공격력 2.5% 증가 공..."

#### 다중으로 넣어도 삼켜진 분노 세트만 나오는 이유는 무엇일까

## 31. 장비 조합 세트 아이템 활성화 정보 조회

In [626]:
url = 'https://api.neople.co.kr/df/custom/equipment/setitems?itemIds=63b8ecd48783be23f0af6a354de9e712,09f62b7d49849f9eb13905b7a1e102e3&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [627]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [630]:
json_normalize(json_ob['equipment'])

,slotId,slotName,itemId,itemName,itemTypeId,itemType,itemTypeDetailId,itemTypeDetail,itemAvailableLevel,itemRarity,setItemId,setItemName
0,FACE,얼굴 아바타,09f62b7d49849f9eb13905b7a1e102e3,차원 여행자의 고글[A타입],5f41b95e310c27783378edde2d24c3dd,아바타,d4722756a5a43ce7a87f5d7cb703df74,얼굴,1,커먼,9f4e37cacf594e02d54669129b7bca53,차원 여행 아바타 세트

In [632]:
json_normalize(json_ob['setItemInfo'])

,setItemId,setItemName,slotInfo,activeSetNo
0,9f4e37cacf594e02d54669129b7bca53,차원 여행 아바타 세트,"[{'slotId': 'FACE', 'slotName': '얼굴 아바타', 'ite...",-1

## 32. 직업 정보

In [633]:
url = 'https://api.neople.co.kr/df/jobs?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [634]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [637]:
json_normalize(json_ob['rows'])

,jobId,jobName,rows
0,41f1cdc2ff58bb5fdc287be0db2a8df3,귀검사(남),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
1,a7a059ebe9e6054c0644b40ef316d6e9,격투가(여),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
2,afdf3b989339de478e85b614d274d1ef,거너(남),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
3,3909d0b188e9c95311399f776e331da5,마법사(여),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
4,f6a4ad30555b99b499c07835f87ce522,프리스트(남),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
5,944b9aab492c15a8474f96947ceeb9e4,거너(여),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
6,ddc49e9ad1ff72a00b53c6cff5b1e920,도적,[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
7,ca0f0e0e9e1d55b5f9955b03d9dd213c,격투가(남),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
8,a5ccbaf5538981c6ef99b236c0a60b73,마법사(남),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
9,17e417b31686389eebff6d754c3401ea,다크나이트,[{'jobGrowId': '4fdee159d5aa8874a1459861ced676...
10,b522a95d819a5559b775deb9a490e49a,크리에이터,[{'jobGrowId': '4fdee159d5aa8874a1459861ced676...
11,1645c45aabb008c98406b3a16447040d,귀검사(여),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
12,0ee8fa5dc525c1a1f23fc6911e921e4a,나이트,[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
13,3deb7be5f01953ac8b1ecaa1e25e0420,마창사,[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
14,0c1b401bb09241570d364420b3ba3fd7,프리스트(여),[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
15,986c2b3d72ee0e4a0b7fcfbe786d4e02,총검사,[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...
16,b9cb48777665de22c006fabaf9a560b3,아처,[{'jobGrowId': 'df3870efe8e8754011cd12fa03cd27...

In [643]:
json_normalize(json_normalize(json_ob['rows'])['rows'][0])

,jobGrowId,jobGrowName,next.jobGrowId,next.jobGrowName,next.next.jobGrowId,next.next.jobGrowName,next.next.next.jobGrowId,next.next.next.jobGrowName
0,df3870efe8e8754011cd12fa03cd275f,웨펀마스터,4ec01f4ae3728c080f28a72213b6df10,검성,80ec67d0356defa46a989914caca5820,검신,37495b941da3b1661bc900e68ef3b2c6,眞 웨펀마스터
1,1ea78ae210f681a799feb4403a5c1e85,소울브링어,981d675414f83b926db5f54e5347eec0,소울테이커,8022a99e29b5e4845985fe1d79a233f3,다크로드,618326026de1a1f1cfba5dbd0b8396e7,眞 소울브링어
2,a9a4ef4552d46e39cf6c874a51126410,버서커,460822c3780a9bc3fbe9485cc89c44a4,헬벤터,15ce2751ab9c8302f39636cdb7c3dcfa,블러드 이블,6d459bc74ba73ee4fe5cdc4655400193,眞 버서커
3,4a1459a4fa3c7f59b6da2e43382ed0b9,아수라,faf8fc6f0cd4c0f84f0035e23bd4fa19,대암흑천,64bbd751c0fcae0e74758b871a2296c1,인다라천,c9b492038ee3ca8d27d7004cf58d59f3,眞 아수라
4,a59ba19824dc3292b6075e29b3862ad3,검귀,a427ec3e94087c64cb4144379c3a0d59,야차,3ff5b661925ac59d1ca290b05ca914cc,악귀나찰,92da05ec93fb43406e193ffb9a2a629b,眞 검귀

### -> 전처리 
1. 각 직업마다 또 여러 직업으로 나뉘는데, 16행 모두 세부직업을 총 하나의 데이터프레임으로 합치기 
2. 데이터프레임 만들 때 상위카테고리(ex. 귀검사 ,격투가)를 컬럼값으로 넣어주기

## 33. 직업 별 스킬 리스트
- 귀검사(남) > 웨펀마스터

In [646]:
url = 'https://api.neople.co.kr/df/skills/41f1cdc2ff58bb5fdc287be0db2a8df3?jobGrowId=df3870efe8e8754011cd12fa03cd275f&apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [647]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [649]:
json_normalize(json_ob['skills'])

,skillId,name,requiredLevel,type,costType
0,eb71e1d82d92c7e1d40500a0dcd77aa6,귀참,1,active,SP
1,dcd536f1674630f01fc9667bb202b851,신속한 무기 교체,1,passive,SP
2,fc7a3f4c2852c832a2f20af63d5d212f,어퍼 슬래쉬,1,active,SP
3,fc458e449ee00b01dbf88d09aae65462,웨펀마스터의 경갑 마스터리,1,passive,SP
4,892ef624d8bf3d7fc045f84825fd6104,기초 방어구 마스터리,1,passive,SP
...,...,...,...,...,...
71,0113c8b1306ca76d208f83f2d093dd62,극 발검술 : 무형참,95,active,SP
72,ad7405c320c23a1a3430307d4d1b03c0,찰나의 깨달음,95,passive,SP
73,5f75a60c73b72ad60bd4321b96b16662,내딛는 한걸음,95,passive,SP
74,8b08f9504167a9c0f3a1d29d71b7943e,천제극섬,100,active,SP
75,3f4ddb4df24a9f78c7778568e80107dd,각성의 실마리,100,passive,SP

## 34. 직업별 스킬 상세 정보 조회
- 귀검사(남)의 스킬 중 귀참에 대한 정보 조회

In [1]:
url = 'https://api.neople.co.kr/df/skills/41f1cdc2ff58bb5fdc287be0db2a8df3/eb71e1d82d92c7e1d40500a0dcd77aa6?apikey=OJnvu6JgglMMwk2pvu1jiWQLBTozkx25'

In [3]:
import requests
import json

In [4]:
response = requests.get(url)
contents = response.text
json_ob = json.loads(contents)

In [8]:
from pandas import json_normalize

In [9]:
df = json_normalize(json_ob)
df

  name  ...                                     levelInfo.rows
0   귀참  ...  [{'level': 1, 'consumeMp': 17, 'coolTime': 6, ...

[1 rows x 16 columns]

In [10]:
df['desc'][0].replace('\n', '')

'무기에 귀신을 소환하여 전방 넓은 범위에 강력한 베기를 행한다.[소울 브링어 귀참 드라이브 습득시]귀참 스킬 키를 지속하여 충전이 가능해지고 타격 후 추가조작으로 귀참 드라이브가 가능해진다.[데모닉 크라운 습득시]충전 기능이 사라지고, 공격시 제자리 베기를 한다. 명계의 힘으로 블레이드 팬텀의 기운을 발생시킨다.'

In [11]:
df['descDetail'][0].replace('\n', '')

'무기에 귀신을 소환하여 전방 넓은 범위에 강력한 암속성 베기를 행한다.[소울 브링어 귀참 드라이브 습득시]귀참 스킬 키를 지속하여 충전이 가능해지고 타격 후 추가조작으로 귀참 드라이브가 가능해진다.[데모닉 크라운 습득시]충전 기능이 사라지고, 공격시 제자리 베기를 한다. 명계의 힘으로 블레이드 팬텀의 기운을 발생시킨다.'

In [12]:
df['descSpecial'][0].replace('\n', '')

'[소울브링어 귀참 드라이브 습득시]- 귀참 충전 가능- 추가 조작시 귀참 드라이브 적용[데모닉 크라운 습득시]- 충전 기능 삭제- 블레이드 팬텀 사출'

In [14]:
import pandas as pd

In [15]:
pd.DataFrame(df['jobGrowLevel'][0])

                          jobGrowId jobGrowName  masterLevel
0  1ea40db11ff66e70bcb0add7fae44cdb      귀검사(남)           60
1  df3870efe8e8754011cd12fa03cd275f       웨펀마스터           60
2  1ea78ae210f681a799feb4403a5c1e85       소울브링어           60
3  a9a4ef4552d46e39cf6c874a51126410         버서커           60
4  4a1459a4fa3c7f59b6da2e43382ed0b9         아수라           60
5  a59ba19824dc3292b6075e29b3862ad3          검귀           60

In [22]:
df#['levelInfo.rows'][0]

  name  ...                                     levelInfo.rows
0   귀참  ...  [{'level': 1, 'consumeMp': 17, 'coolTime': 6, ...

[1 rows x 16 columns]

In [20]:
json_normalize(df['levelInfo.rows'][0])

    level  consumeMp  ...  optionValue.value9 optionValue.value10
0       1         17  ...                 973                 100
1       2         19  ...                1094                 100
2       3         22  ...                1216                 100
3       4         24  ...                1335                 100
4       5         27  ...                1452                 100
..    ...        ...  ...                 ...                 ...
65     66        185  ...                8730                 100
66     67        188  ...                8849                 100
67     68        190  ...                8973                 100
68     69        193  ...                9088                 100
69     70        196  ...                9212                 100

[70 rows x 14 columns]

In [17]:
list(filter(bool, df['levelInfo.optionDesc'][0].split('\n')))

['마법 무기 공격력 : {value1}%',
 '[소울 브링어 귀참 드라이브 습득시]',
 '최대 충전시 공격력 증가율: {value2}%',
 '귀신 추가 공격력 : {value3}%',
 '[사야 공격시]',
 '빙결 확률 : {value4}%',
 '빙결 유지시간 : {value5}초',
 '[브레멘 공격시]',
 '수면 확률 : {value6}%',
 '수면 유지시간 : {value7}초',
 '[데모닉 크라운 습득시]',
 '귀신 베기 공격력 : {value8}%',
 '블레이드 팬텀 공격력 : {value9}%',
 '[범위 정보]',
 '베기 범위 비율 : {value10}%']

In [668]:
df['levelInfo.rows'][0]

[{'level': 1,
  'consumeMp': 17,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1001,
   'value2': 20,
   'value3': 973,
   'value4': 90,
   'value5': 1.9,
   'value6': 90,
   'value7': 5,
   'value8': 1001,
   'value9': 973,
   'value10': 100}},
 {'level': 2,
  'consumeMp': 19,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1124,
   'value2': 20,
   'value3': 1094,
   'value4': 90,
   'value5': 1.9,
   'value6': 90,
   'value7': 4.5,
   'value8': 1124,
   'value9': 1094,
   'value10': 100}},
 {'level': 3,
  'consumeMp': 22,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1249,
   'value2': 20,
   'value3': 1216,
   'value4': 90,
   'value5': 1.9,
   'value6': 90,
   'value7': 4.5,
   'value8': 1249,
   'value9': 1216,
   'value10': 100}},
 {'level': 4,
  'consumeMp': 24,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1371,
   'value2': 20,
   'value3': 1335,
   'value4': 90,
   'value5': 1.9,
   'value6': 90,
   'value7': 4.5,
   'value8': 1371,
   'value9': 1335,
   'value10': 100}},
 {'level': 5,
  'consumeMp': 27,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1493,
   'value2': 20,
   'value3': 1452,
   'value4': 91,
   'value5': 1.9,
   'value6': 91,
   'value7': 4.5,
   'value8': 1493,
   'value9': 1452,
   'value10': 100}},
 {'level': 6,
  'consumeMp': 29,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1614,
   'value2': 20,
   'value3': 1570,
   'value4': 91,
   'value5': 1.9,
   'value6': 91,
   'value7': 4.5,
   'value8': 1614,
   'value9': 1570,
   'value10': 100}},
 {'level': 7,
  'consumeMp': 32,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1738,
   'value2': 20,
   'value3': 1690,
   'value4': 91,
   'value5': 2,
   'value6': 91,
   'value7': 4.5,
   'value8': 1738,
   'value9': 1690,
   'value10': 100}},
 {'level': 8,
  'consumeMp': 35,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1864,
   'value2': 20,
   'value3': 1812,
   'value4': 91,
   'value5': 2,
   'value6': 91,
   'value7': 4.5,
   'value8': 1864,
   'value9': 1812,
   'value10': 100}},
 {'level': 9,
  'consumeMp': 37,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 1987,
   'value2': 20,
   'value3': 1932,
   'value4': 91,
   'value5': 2,
   'value6': 91,
   'value7': 4.5,
   'value8': 1987,
   'value9': 1932,
   'value10': 100}},
 {'level': 10,
  'consumeMp': 40,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2109,
   'value2': 20,
   'value3': 2050,
   'value4': 92,
   'value5': 2,
   'value6': 92,
   'value7': 4.5,
   'value8': 2109,
   'value9': 2050,
   'value10': 100}},
 {'level': 11,
  'consumeMp': 42,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2229,
   'value2': 20,
   'value3': 2167,
   'value4': 92,
   'value5': 2,
   'value6': 92,
   'value7': 4.5,
   'value8': 2229,
   'value9': 2167,
   'value10': 100}},
 {'level': 12,
  'consumeMp': 45,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2356,
   'value2': 20,
   'value3': 2287,
   'value4': 92,
   'value5': 2,
   'value6': 92,
   'value7': 4.5,
   'value8': 2356,
   'value9': 2287,
   'value10': 100}},
 {'level': 13,
  'consumeMp': 48,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2474,
   'value2': 20,
   'value3': 2407,
   'value4': 92,
   'value5': 2,
   'value6': 92,
   'value7': 4.5,
   'value8': 2474,
   'value9': 2407,
   'value10': 100}},
 {'level': 14,
  'consumeMp': 50,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2595,
   'value2': 20,
   'value3': 2526,
   'value4': 92,
   'value5': 2.1,
   'value6': 92,
   'value7': 4.5,
   'value8': 2595,
   'value9': 2526,
   'value10': 100}},
 {'level': 15,
  'consumeMp': 53,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2718,
   'value2': 20,
   'value3': 2648,
   'value4': 93,
   'value5': 2.1,
   'value6': 93,
   'value7': 4.5,
   'value8': 2718,
   'value9': 2648,
   'value10': 100}},
 {'level': 16,
  'consumeMp': 55,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2844,
   'value2': 20,
   'value3': 2766,
   'value4': 93,
   'value5': 2.1,
   'value6': 93,
   'value7': 4.5,
   'value8': 2844,
   'value9': 2766,
   'value10': 100}},
 {'level': 17,
  'consumeMp': 58,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 2963,
   'value2': 20,
   'value3': 2883,
   'value4': 93,
   'value5': 2.1,
   'value6': 93,
   'value7': 4.5,
   'value8': 2963,
   'value9': 2883,
   'value10': 100}},
 {'level': 18,
  'consumeMp': 61,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3086,
   'value2': 20,
   'value3': 3001,
   'value4': 93,
   'value5': 2.1,
   'value6': 93,
   'value7': 4.5,
   'value8': 3086,
   'value9': 3001,
   'value10': 100}},
 {'level': 19,
  'consumeMp': 63,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3211,
   'value2': 20,
   'value3': 3123,
   'value4': 93,
   'value5': 2.1,
   'value6': 93,
   'value7': 4.5,
   'value8': 3211,
   'value9': 3123,
   'value10': 100}},
 {'level': 20,
  'consumeMp': 66,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3330,
   'value2': 20,
   'value3': 3242,
   'value4': 94,
   'value5': 2.2,
   'value6': 94,
   'value7': 4.5,
   'value8': 3330,
   'value9': 3242,
   'value10': 100}},
 {'level': 21,
  'consumeMp': 68,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3459,
   'value2': 20,
   'value3': 3366,
   'value4': 94,
   'value5': 2.2,
   'value6': 94,
   'value7': 4.5,
   'value8': 3459,
   'value9': 3366,
   'value10': 100}},
 {'level': 22,
  'consumeMp': 71,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3581,
   'value2': 20,
   'value3': 3481,
   'value4': 94,
   'value5': 2.2,
   'value6': 94,
   'value7': 4.5,
   'value8': 3581,
   'value9': 3481,
   'value10': 100}},
 {'level': 23,
  'consumeMp': 74,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3701,
   'value2': 20,
   'value3': 3601,
   'value4': 94,
   'value5': 2.2,
   'value6': 94,
   'value7': 4.5,
   'value8': 3701,
   'value9': 3601,
   'value10': 100}},
 {'level': 24,
  'consumeMp': 76,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3824,
   'value2': 20,
   'value3': 3718,
   'value4': 94,
   'value5': 2.2,
   'value6': 94,
   'value7': 4.5,
   'value8': 3824,
   'value9': 3718,
   'value10': 100}},
 {'level': 25,
  'consumeMp': 79,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 3947,
   'value2': 20,
   'value3': 3839,
   'value4': 95,
   'value5': 2.2,
   'value6': 95,
   'value7': 4.5,
   'value8': 3947,
   'value9': 3839,
   'value10': 100}},
 {'level': 26,
  'consumeMp': 81,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4068,
   'value2': 20,
   'value3': 3957,
   'value4': 95,
   'value5': 2.3,
   'value6': 95,
   'value7': 4.5,
   'value8': 4068,
   'value9': 3957,
   'value10': 100}},
 {'level': 27,
  'consumeMp': 84,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4194,
   'value2': 20,
   'value3': 4081,
   'value4': 95,
   'value5': 2.3,
   'value6': 95,
   'value7': 4.5,
   'value8': 4194,
   'value9': 4081,
   'value10': 100}},
 {'level': 28,
  'consumeMp': 87,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4315,
   'value2': 20,
   'value3': 4199,
   'value4': 95,
   'value5': 2.3,
   'value6': 95,
   'value7': 4.5,
   'value8': 4315,
   'value9': 4199,
   'value10': 100}},
 {'level': 29,
  'consumeMp': 89,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4438,
   'value2': 20,
   'value3': 4316,
   'value4': 95,
   'value5': 2.3,
   'value6': 95,
   'value7': 4.5,
   'value8': 4438,
   'value9': 4316,
   'value10': 100}},
 {'level': 30,
  'consumeMp': 92,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4559,
   'value2': 20,
   'value3': 4434,
   'value4': 96,
   'value5': 2.3,
   'value6': 96,
   'value7': 4.5,
   'value8': 4559,
   'value9': 4434,
   'value10': 100}},
 {'level': 31,
  'consumeMp': 94,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4683,
   'value2': 20,
   'value3': 4554,
   'value4': 96,
   'value5': 2.3,
   'value6': 96,
   'value7': 4.5,
   'value8': 4683,
   'value9': 4554,
   'value10': 100}},
 {'level': 32,
  'consumeMp': 97,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4804,
   'value2': 20,
   'value3': 4674,
   'value4': 96,
   'value5': 2.3,
   'value6': 96,
   'value7': 4.5,
   'value8': 4804,
   'value9': 4674,
   'value10': 100}},
 {'level': 33,
  'consumeMp': 100,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 4931,
   'value2': 20,
   'value3': 4797,
   'value4': 96,
   'value5': 2.4,
   'value6': 96,
   'value7': 4.5,
   'value8': 4931,
   'value9': 4797,
   'value10': 100}},
 {'level': 34,
  'consumeMp': 102,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5054,
   'value2': 20,
   'value3': 4914,
   'value4': 96,
   'value5': 2.4,
   'value6': 96,
   'value7': 4.5,
   'value8': 5054,
   'value9': 4914,
   'value10': 100}},
 {'level': 35,
  'consumeMp': 105,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5174,
   'value2': 20,
   'value3': 5032,
   'value4': 97,
   'value5': 2.4,
   'value6': 97,
   'value7': 4.5,
   'value8': 5174,
   'value9': 5032,
   'value10': 100}},
 {'level': 36,
  'consumeMp': 107,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5296,
   'value2': 20,
   'value3': 5149,
   'value4': 97,
   'value5': 2.4,
   'value6': 97,
   'value7': 4.5,
   'value8': 5296,
   'value9': 5149,
   'value10': 100}},
 {'level': 37,
  'consumeMp': 110,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5418,
   'value2': 20,
   'value3': 5271,
   'value4': 97,
   'value5': 2.4,
   'value6': 97,
   'value7': 4.5,
   'value8': 5418,
   'value9': 5271,
   'value10': 100}},
 {'level': 38,
  'consumeMp': 112,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5543,
   'value2': 20,
   'value3': 5390,
   'value4': 97,
   'value5': 2.4,
   'value6': 97,
   'value7': 4.5,
   'value8': 5543,
   'value9': 5390,
   'value10': 100}},
 {'level': 39,
  'consumeMp': 115,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5664,
   'value2': 20,
   'value3': 5511,
   'value4': 97,
   'value5': 2.4,
   'value6': 97,
   'value7': 4.5,
   'value8': 5664,
   'value9': 5511,
   'value10': 100}},
 {'level': 40,
  'consumeMp': 118,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5787,
   'value2': 20,
   'value3': 5631,
   'value4': 98,
   'value5': 2.5,
   'value6': 98,
   'value7': 4.5,
   'value8': 5787,
   'value9': 5631,
   'value10': 100}},
 {'level': 41,
  'consumeMp': 120,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 5908,
   'value2': 20,
   'value3': 5748,
   'value4': 98,
   'value5': 2.5,
   'value6': 98,
   'value7': 4.5,
   'value8': 5908,
   'value9': 5748,
   'value10': 100}},
 {'level': 42,
  'consumeMp': 123,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6030,
   'value2': 20,
   'value3': 5866,
   'value4': 98,
   'value5': 2.5,
   'value6': 98,
   'value7': 4.5,
   'value8': 6030,
   'value9': 5866,
   'value10': 100}},
 {'level': 43,
  'consumeMp': 125,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6155,
   'value2': 20,
   'value3': 5987,
   'value4': 98,
   'value5': 2.5,
   'value6': 98,
   'value7': 4.5,
   'value8': 6155,
   'value9': 5987,
   'value10': 100}},
 {'level': 44,
  'consumeMp': 128,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6277,
   'value2': 20,
   'value3': 6107,
   'value4': 98,
   'value5': 2.5,
   'value6': 98,
   'value7': 4.5,
   'value8': 6277,
   'value9': 6107,
   'value10': 100}},
 {'level': 45,
  'consumeMp': 131,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6399,
   'value2': 20,
   'value3': 6225,
   'value4': 99,
   'value5': 2.5,
   'value6': 99,
   'value7': 4.5,
   'value8': 6399,
   'value9': 6225,
   'value10': 100}},
 {'level': 46,
  'consumeMp': 133,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6524,
   'value2': 20,
   'value3': 6346,
   'value4': 99,
   'value5': 2.5,
   'value6': 99,
   'value7': 4.5,
   'value8': 6524,
   'value9': 6346,
   'value10': 100}},
 {'level': 47,
  'consumeMp': 136,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6646,
   'value2': 20,
   'value3': 6463,
   'value4': 99,
   'value5': 2.6,
   'value6': 99,
   'value7': 4.5,
   'value8': 6646,
   'value9': 6463,
   'value10': 100}},
 {'level': 48,
  'consumeMp': 138,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6768,
   'value2': 20,
   'value3': 6581,
   'value4': 99,
   'value5': 2.6,
   'value6': 99,
   'value7': 4.5,
   'value8': 6768,
   'value9': 6581,
   'value10': 100}},
 {'level': 49,
  'consumeMp': 141,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 6893,
   'value2': 20,
   'value3': 6704,
   'value4': 99,
   'value5': 2.6,
   'value6': 99,
   'value7': 4.5,
   'value8': 6893,
   'value9': 6704,
   'value10': 100}},
 {'level': 50,
  'consumeMp': 144,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7015,
   'value2': 20,
   'value3': 6822,
   'value4': 100,
   'value5': 2.6,
   'value6': 100,
   'value7': 4.5,
   'value8': 7015,
   'value9': 6822,
   'value10': 100}},
 {'level': 51,
  'consumeMp': 146,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7137,
   'value2': 20,
   'value3': 6940,
   'value4': 100,
   'value5': 2.6,
   'value6': 100,
   'value7': 4.5,
   'value8': 7137,
   'value9': 6940,
   'value10': 100}},
 {'level': 52,
  'consumeMp': 149,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7260,
   'value2': 20,
   'value3': 7060,
   'value4': 100,
   'value5': 2.6,
   'value6': 100,
   'value7': 4.5,
   'value8': 7260,
   'value9': 7060,
   'value10': 100}},
 {'level': 53,
  'consumeMp': 151,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7385,
   'value2': 20,
   'value3': 7183,
   'value4': 100,
   'value5': 2.6,
   'value6': 100,
   'value7': 4.5,
   'value8': 7385,
   'value9': 7183,
   'value10': 100}},
 {'level': 54,
  'consumeMp': 154,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7503,
   'value2': 20,
   'value3': 7299,
   'value4': 100,
   'value5': 2.7,
   'value6': 100,
   'value7': 4.5,
   'value8': 7503,
   'value9': 7299,
   'value10': 100}},
 {'level': 55,
  'consumeMp': 157,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7630,
   'value2': 20,
   'value3': 7419,
   'value4': 101,
   'value5': 2.7,
   'value6': 101,
   'value7': 4.5,
   'value8': 7630,
   'value9': 7419,
   'value10': 100}},
 {'level': 56,
  'consumeMp': 159,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7750,
   'value2': 20,
   'value3': 7540,
   'value4': 101,
   'value5': 2.7,
   'value6': 101,
   'value7': 4.5,
   'value8': 7750,
   'value9': 7540,
   'value10': 100}},
 {'level': 57,
  'consumeMp': 162,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7873,
   'value2': 20,
   'value3': 7657,
   'value4': 101,
   'value5': 2.7,
   'value6': 101,
   'value7': 4.5,
   'value8': 7873,
   'value9': 7657,
   'value10': 100}},
 {'level': 58,
  'consumeMp': 164,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 7999,
   'value2': 20,
   'value3': 7778,
   'value4': 101,
   'value5': 2.7,
   'value6': 101,
   'value7': 4.5,
   'value8': 7999,
   'value9': 7778,
   'value10': 100}},
 {'level': 59,
  'consumeMp': 167,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8120,
   'value2': 20,
   'value3': 7900,
   'value4': 101,
   'value5': 2.7,
   'value6': 101,
   'value7': 4.5,
   'value8': 8120,
   'value9': 7900,
   'value10': 100}},
 {'level': 60,
  'consumeMp': 170,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8242,
   'value2': 20,
   'value3': 8016,
   'value4': 102,
   'value5': 2.8,
   'value6': 102,
   'value7': 4.5,
   'value8': 8242,
   'value9': 8016,
   'value10': 100}},
 {'level': 61,
  'consumeMp': 172,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8365,
   'value2': 20,
   'value3': 8135,
   'value4': 102,
   'value5': 2.8,
   'value6': 102,
   'value7': 4.5,
   'value8': 8365,
   'value9': 8135,
   'value10': 100}},
 {'level': 62,
  'consumeMp': 175,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8488,
   'value2': 20,
   'value3': 8255,
   'value4': 102,
   'value5': 2.8,
   'value6': 102,
   'value7': 4.5,
   'value8': 8488,
   'value9': 8255,
   'value10': 100}},
 {'level': 63,
  'consumeMp': 177,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8608,
   'value2': 20,
   'value3': 8372,
   'value4': 102,
   'value5': 2.8,
   'value6': 102,
   'value7': 4.5,
   'value8': 8608,
   'value9': 8372,
   'value10': 100}},
 {'level': 64,
  'consumeMp': 180,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8733,
   'value2': 20,
   'value3': 8494,
   'value4': 102,
   'value5': 2.8,
   'value6': 102,
   'value7': 4.5,
   'value8': 8733,
   'value9': 8494,
   'value10': 100}},
 {'level': 65,
  'consumeMp': 183,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8854,
   'value2': 20,
   'value3': 8614,
   'value4': 103,
   'value5': 2.8,
   'value6': 103,
   'value7': 4.5,
   'value8': 8854,
   'value9': 8614,
   'value10': 100}},
 {'level': 66,
  'consumeMp': 185,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 8974,
   'value2': 20,
   'value3': 8730,
   'value4': 103,
   'value5': 2.9,
   'value6': 103,
   'value7': 4.5,
   'value8': 8974,
   'value9': 8730,
   'value10': 100}},
 {'level': 67,
  'consumeMp': 188,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 9097,
   'value2': 20,
   'value3': 8849,
   'value4': 103,
   'value5': 2.9,
   'value6': 103,
   'value7': 4.5,
   'value8': 9097,
   'value9': 8849,
   'value10': 100}},
 {'level': 68,
  'consumeMp': 190,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 9223,
   'value2': 20,
   'value3': 8973,
   'value4': 103,
   'value5': 2.9,
   'value6': 103,
   'value7': 4.5,
   'value8': 9223,
   'value9': 8973,
   'value10': 100}},
 {'level': 69,
  'consumeMp': 193,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 9344,
   'value2': 20,
   'value3': 9088,
   'value4': 103,
   'value5': 2.9,
   'value6': 103,
   'value7': 4.5,
   'value8': 9344,
   'value9': 9088,
   'value10': 100}},
 {'level': 70,
  'consumeMp': 196,
  'coolTime': 6,
  'castingTime': None,
  'optionValue': {'value1': 9469,
   'value2': 20,
   'value3': 9212,
   'value4': 104,
   'value5': 2.9,
   'value6': 104,
   'value7': 4.5,
   'value8': 9469,
   'value9': 9212,
   'value10': 100}}]